'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const html=fs.readFileSync(path.join(__dirname,'../../hosting/wallet/wallet-live.html'),'utf8');
function harness(){let poll,hidden=false;const context={walletProvider:null,walletAccount:null,walletName:'',walletConnecting:false,
 $:()=>({classList:{add:()=>hidden=true,remove:()=>hidden=false,contains:()=>hidden}}),updateWalletButton(){},fillRecipientFields(){},watchAccountChanges(){},log(){},renderWalletList(){},setInterval:fn=>(poll=fn,1),clearInterval(){}};
 vm.createContext(context);vm.runInContext(html.slice(html.indexOf('async function selectWallet('),html.indexOf('function fillRecipientFields(')),context);vm.runInContext(html.slice(html.indexOf('async function ensureWallet('),html.indexOf('/**\n * `/api/deposit-info`')),context);return {context,poll:()=>poll(),close:()=>hidden=true};}
test('Join waits for slow wallet approval after the picker closes',async()=>{const h=harness(),c=h.context;let approve,done=false;const waiting=c.ensureWallet().then(()=>done=true);const selection=c.selectWallet({info:{name:'wallet'},provider:{request:()=>new Promise(r=>approve=r)}});h.poll();await Promise.resolve();assert.equal(done,false);approve(['account']);await selection;h.poll();await waiting;assert.equal(done,true);});
test('closing the picker rejects the pending action instead of leaving Join disabled forever',async()=>{const h=harness();const waiting=h.context.ensureWallet();h.close();h.poll();await assert.rejects(waiting,/not selected/);});
test('wallet rejection after slow approval releases the pending action',async()=>{const h=harness();let reject;const waiting=h.context.ensureWallet();const selection=h.context.selectWallet({info:{name:'wallet'},provider:{request:()=>new Promise((_,r)=>reject=r)}});h.poll();reject(Error('user rejected'));await selection;h.poll();await assert.rejects(waiting,/not selected/);assert.equal(h.context.walletConnecting,false);});
