//! Non-skipping, proof-free release audit for every checked-in live MLE/WHIR v2 artifact.
//!
//! Heavy statement E2Es prove and verify the circuits. This gate protects the artifact boundary:
//! exact full/config schemas, canonical JSON, full↔config identity, compact decode/re-encode
//! uniqueness, redundant ABI-view agreement, and submission/Proof-DA metadata over the exact
//! compact bytes. It deliberately scans the directory as well as using a manifest so adding a new
//! live `*_mle.json` cannot silently escape the release gate.

use std::{collections::BTreeSet, fs, path::PathBuf};

use intmax3_zkp::{
    circuits::{
        channel::{
            cancel_close_pis::CancelClosePublicInputs,
            close_asset_backing_circuit::{
                CLOSE_ASSET_BACKING_PUBLIC_INPUTS_LEN, CloseAssetBackingPublicInputs,
            },
            close_pis::ChannelClosePublicInputs,
            post_close_claim_pis::PostCloseClaimPublicInputs,
            withdrawal_claim_pis::WithdrawalClaimPublicInputs,
        },
        validity::block_hash_chain::validity_circuit::ValidityPublicInputs,
        withdraw::withdrawal_circuit::WithdrawalProofPublicInputs,
    },
    common::{
        balance_state::settled_tx_chain_push,
        channel::{close_member_set_commitment, token_funds_digest},
        u63::BlockNumber,
        withdrawal::Withdrawal,
    },
    constants::{MAX_CHANNEL_TOKENS, MAX_SIG_CLUSTER},
    ethereum_types::{address::Address, bytes32::Bytes32, u32limb_trait::U32LimbTrait, u256::U256},
    public_close_prover::PUBLIC_CLOSE_BUNDLE_SCHEMA_VERSION,
    utils::mle_prover::{
        mle_v2_compact_submission_metadata, validate_mle_v2_full_against_config_json,
    },
};
use plonky2_mle::{
    fixture_v2::{
        MLE_VERIFIER_CONFIG_FIXTURE_SCHEMA_V2, MLE_VERIFIER_FIXTURE_SCHEMA_V2,
        MleVerifierV2ConfigFixture, MleVerifierV2Fixture,
    },
    protocol_schema_v2::{
        COMPACT_MAGIC_V2, MLE_PROTOCOL_VERSION_CURRENT, SCHEMA_VERSION_CURRENT, WHIR_POW_BITS_V2,
    },
};
use serde::Deserialize;
use sha2::{Digest, Sha256};

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn data_path(name: &str) -> PathBuf {
    repo_root().join("contracts/test/data").join(name)
}

fn read(name: &str) -> String {
    let path = data_path(name);
    fs::read_to_string(&path).unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()))
}

fn parse_config(name: &str) -> MleVerifierV2ConfigFixture {
    MleVerifierV2ConfigFixture::from_canonical_json(&read(name))
        .unwrap_or_else(|e| panic!("{name} is not a strict canonical proof-free V2 config: {e}"))
}

/// Every top-level checked-in live full proof and its proof-free deployment configuration.
/// Prefix variants of the same statement still appear independently because their witness/proof
/// and downstream descriptors are distinct release artifacts.
const LIVE_FULL_CONFIG_PAIRS: &[(&str, &str)] = &[
    ("mle_fixture.json", "mle_fixture_config.json"),
    (
        "lifecycle_validity_mle.json",
        "lifecycle_validity_mle_config.json",
    ),
    ("withdrawal_mle.json", "withdrawal_mle_config.json"),
    (
        "close_lifecycle_validity_mle.json",
        "close_lifecycle_validity_mle_config.json",
    ),
    (
        "close_withdrawal_mle.json",
        "close_withdrawal_mle_config.json",
    ),
    ("close_intent_mle.json", "close_intent_mle_config.json"),
    // The whole-vector CloseAssetBacking statement pinned by `CloseFundingMaterializer`.
    (
        "close_asset_backing_mle.json",
        "close_asset_backing_mle_config.json",
    ),
    (
        "withdrawal_claim_mle.json",
        "withdrawal_claim_mle_config.json",
    ),
    (
        "post_close_claim_mle.json",
        "post_close_claim_mle_config.json",
    ),
    ("cancel_close_mle.json", "cancel_close_mle_config.json"),
    (
        "c2c_lifecycle_validity_mle.json",
        "c2c_lifecycle_validity_mle_config.json",
    ),
    ("c2c_withdrawal_mle.json", "c2c_withdrawal_mle_config.json"),
    (
        "burn_lifecycle_validity_mle.json",
        "burn_lifecycle_validity_mle_config.json",
    ),
    (
        "burn_withdrawal_mle.json",
        "burn_withdrawal_mle_config.json",
    ),
    // This proof is generated by the live partial-withdrawal E2E using the same close circuit.
    ("pw_close_intent_mle.json", "close_intent_mle_config.json"),
    (
        "sepolia_lifecycle_validity_mle.json",
        "sepolia_lifecycle_validity_mle_config.json",
    ),
    (
        "sepolia_withdrawal_mle.json",
        "sepolia_withdrawal_mle_config.json",
    ),
];

/// Complete proof-free cohort produced before deployment. This manifest is deliberately
/// independent of the full-proof manifest: during a protocol cutover every old full proof is
/// expected to be temporarily incompatible while all configs must already form one deployable
/// generation. A missing, old, or mixed config therefore fails before any verifier is deployed.
const LIVE_CONFIG_COHORT: &[&str] = &[
    "burn_lifecycle_validity_mle_config.json",
    "burn_withdrawal_mle_config.json",
    "c2c_lifecycle_validity_mle_config.json",
    "c2c_withdrawal_mle_config.json",
    "cancel_close_mle_config.json",
    "close_asset_backing_mle_config.json",
    "close_intent_mle_config.json",
    "close_lifecycle_validity_mle_config.json",
    "close_withdrawal_mle_config.json",
    "lifecycle_validity_mle_config.json",
    "mle_fixture_config.json",
    "post_close_claim_mle_config.json",
    "sepolia_lifecycle_validity_mle_config.json",
    "sepolia_withdrawal_mle_config.json",
    "withdrawal_claim_mle_config.json",
    "withdrawal_mle_config.json",
];

/// Validity proofs whose companion descriptor supplies `postBlockAndSubmit` / Proof-DA metadata.
const VALIDITY_DA_COMPANIONS: &[(&str, &str, &str)] = &[
    (
        "mle_fixture.json",
        "mle_fixture_config.json",
        "block_fixture.json",
    ),
    (
        "lifecycle_validity_mle.json",
        "lifecycle_validity_mle_config.json",
        "lifecycle.json",
    ),
    (
        "close_lifecycle_validity_mle.json",
        "close_lifecycle_validity_mle_config.json",
        "close_lifecycle.json",
    ),
    (
        "c2c_lifecycle_validity_mle.json",
        "c2c_lifecycle_validity_mle_config.json",
        "c2c_lifecycle.json",
    ),
    (
        "burn_lifecycle_validity_mle.json",
        "burn_lifecycle_validity_mle_config.json",
        "burn_lifecycle.json",
    ),
    (
        "sepolia_lifecycle_validity_mle.json",
        "sepolia_lifecycle_validity_mle_config.json",
        "sepolia_lifecycle.json",
    ),
];

/// The only seven statement configurations admitted by the current parent release. The generic
/// submodule decoder has wider defensive parser caps; those caps are not a claim that every axis
/// can be combined inside the 30M production envelope. Adding or changing a parent statement must
/// update this explicit table and receive its own real-proof size/gas admission. The digest pins
/// the complete canonical Solidity constructor configuration (including every gate row and WHIR
/// parameter); the separate on-chain gas suites admit the matching real proofs.
const PRODUCTION_RESOURCE_PROFILES: &[(&str, usize, usize, usize, usize, &str)] = &[
    // config, public inputs, constants, selectors, exact compact grammar maximum, config ABI hash
    (
        "mle_fixture_config.json",
        8,
        5,
        3,
        133_612,
        "0xaa6bbe608a91653b95715f7555eec2306131078c999788911a0bd6a61327c4c3",
    ),
    (
        "withdrawal_mle_config.json",
        17,
        5,
        3,
        133_684,
        "0x1696fa601bd337acf25fe330034ee06356615ab4105ffc0d1f01e0f37cf8d1fb",
    ),
    (
        "close_intent_mle_config.json",
        103,
        5,
        3,
        134_372,
        "0x5a3b3fb9cb0582c16b4f5b1ecb2b9833b87c9d5c1357766b0ebcc88386d1ebd1",
    ),
    (
        "withdrawal_claim_mle_config.json",
        50,
        6,
        4,
        133_996,
        "0x7c8e8980632d9295f6d0ec6eb1e5d6da9ebbf7fd63522519d0f48d544c8d40c7",
    ),
    (
        "post_close_claim_mle_config.json",
        57,
        6,
        4,
        134_052,
        "0x2f4696d900a8b9b3fbdbcdb4fb3614855d5b09ef25d7412c33e7dad7a18020a6",
    ),
    (
        "cancel_close_mle_config.json",
        29,
        5,
        3,
        133_780,
        "0xa455e9b6c5e782779c23db6a61948bd91660e4ff12a4b571779a5362390a317f",
    ),
    (
        "close_asset_backing_mle_config.json",
        26,
        5,
        3,
        133_756,
        "0xb2c6af6fedf9d0e485ce6cfa380db8942982e62ba2592396b3f1fca98d383bde",
    ),
];

/// One atomic generator invocation and every tracked JSON artifact it owns. The entries below are
/// the complete release-producing surface; putting companions in the manifest makes it impossible
/// to regenerate a proof/config while silently retaining a descriptor from another generation.
struct GeneratorCohort {
    invocation: &'static str,
    configs: &'static [&'static str],
    full_proofs: &'static [&'static str],
    companions: &'static [&'static str],
}

const GENERATOR_COHORTS: &[GeneratorCohort] = &[
    GeneratorCohort {
        invocation: "generate_e2e_fixture",
        configs: &["mle_fixture_config.json"],
        full_proofs: &["mle_fixture.json"],
        companions: &["block_fixture.json", "vpi_fixture.json"],
    },
    GeneratorCohort {
        invocation: "generate_withdrawal_fixture (no prefix)",
        configs: &[
            "lifecycle_validity_mle_config.json",
            "withdrawal_mle_config.json",
        ],
        full_proofs: &["lifecycle_validity_mle.json", "withdrawal_mle.json"],
        companions: &["lifecycle.json", "withdrawal_payout.json"],
    },
    GeneratorCohort {
        invocation: "generate_withdrawal_fixture (WD_OUT_PREFIX=sepolia_)",
        configs: &[
            "sepolia_lifecycle_validity_mle_config.json",
            "sepolia_withdrawal_mle_config.json",
        ],
        full_proofs: &[
            "sepolia_lifecycle_validity_mle.json",
            "sepolia_withdrawal_mle.json",
        ],
        companions: &["sepolia_lifecycle.json", "sepolia_withdrawal_payout.json"],
    },
    GeneratorCohort {
        invocation: "generate_burn_withdrawal_fixture",
        configs: &[
            "burn_lifecycle_validity_mle_config.json",
            "burn_withdrawal_mle_config.json",
        ],
        full_proofs: &[
            "burn_lifecycle_validity_mle.json",
            "burn_withdrawal_mle.json",
        ],
        companions: &["burn_lifecycle.json", "burn_withdrawal_payout.json"],
    },
    GeneratorCohort {
        invocation: "generate_c2c_fixture",
        configs: &[
            "c2c_lifecycle_validity_mle_config.json",
            "c2c_withdrawal_mle_config.json",
        ],
        full_proofs: &["c2c_lifecycle_validity_mle.json", "c2c_withdrawal_mle.json"],
        companions: &["c2c_lifecycle.json", "c2c_withdrawal_payout.json"],
    },
    // The close family is co-generated from ONE lifecycle: the `close_` lifecycle/withdrawal
    // set (`WD_OUT_PREFIX=close_ generate_withdrawal_fixture` is refused), the close intent over
    // that lifecycle's finalized root and the whole-vector CloseAssetBacking proof over the same
    // final balance proof. `submitCloseIntent` only accepts the three together.
    GeneratorCohort {
        invocation: "generate_close_fixture",
        configs: &[
            "close_lifecycle_validity_mle_config.json",
            "close_withdrawal_mle_config.json",
            "close_intent_mle_config.json",
            "close_asset_backing_mle_config.json",
        ],
        full_proofs: &[
            "close_lifecycle_validity_mle.json",
            "close_withdrawal_mle.json",
            "close_intent_mle.json",
            "close_asset_backing_mle.json",
        ],
        companions: &[
            "close_lifecycle.json",
            "close_withdrawal_payout.json",
            "close_intent.json",
            "close_asset_backing_public_inputs.json",
            "close_asset_backing_manifest.json",
        ],
    },
    GeneratorCohort {
        invocation: "generate_withdrawal_claim_fixture",
        configs: &["withdrawal_claim_mle_config.json"],
        full_proofs: &["withdrawal_claim_mle.json"],
        companions: &["withdrawal_claim.json"],
    },
    GeneratorCohort {
        invocation: "generate_post_close_claim_fixture",
        configs: &["post_close_claim_mle_config.json"],
        full_proofs: &["post_close_claim_mle.json"],
        companions: &["post_close_claim.json"],
    },
    GeneratorCohort {
        invocation: "generate_cancel_close_fixture",
        configs: &["cancel_close_mle_config.json"],
        full_proofs: &["cancel_close_mle.json"],
        companions: &["cancel_close.json"],
    },
    GeneratorCohort {
        invocation: "partial_withdrawal_e2e",
        // This E2E reuses the already generated close verifier configuration.
        configs: &[],
        full_proofs: &["pw_close_intent_mle.json"],
        companions: &["pw_reg.json", "pw_submit.json"],
    },
];

/// Tracked JSON in `contracts/test/data` which intentionally is not emitted by the live MLE
/// generator cohort. Keeping the exception list explicit prevents a new stale artifact from being
/// disguised as an unrelated legacy file.
const INTENTIONAL_NON_COHORT_JSON: &[&str] = &[
    "cli_reg_record_guard.json",
    "e2e_fixture.json",
    "e2e_groth16.json",
    "pw_reg_guard.json",
];

/// `generate_wasm_fixtures` owns these binary outputs. They are deliberately outside the 53-file
/// JSON cutover and are never treated as proof/config/descriptor aliases.
const INTENTIONAL_WASM_BINARY_OUTPUTS: &[&str] = &[
    "spend_circuit.bin",
    "balance_processor.bin",
    "single_withdrawal_circuit.bin",
];

/// Exact tracked Solidity-fixture surface in the pinned MLE submodule. The seven packed-v1 files
/// remain historical cross-language conformance inputs, not aliases for the current wire-v3
/// deployment protocol. `xlarge_mul.json` was retired and its reappearance must fail the release
/// gate rather than silently expanding the legacy surface.
const SUBMODULE_SOLIDITY_FIXTURES: &[&str] = &[
    "coset_recursive_verify.json",
    "historical_pcs_triples.json",
    "huge_mul.json",
    "large_mul.json",
    "medium_mul.json",
    "poseidon_hash.json",
    "recursive_verify.json",
    "small_mul.json",
    "transcript_v1_trace.json",
    "v2_cross_language.json",
    "v2_max_resource.json",
];

const SUBMODULE_PACKED_V1_FIXTURES: &[&str] = &[
    "coset_recursive_verify.json",
    "huge_mul.json",
    "large_mul.json",
    "medium_mul.json",
    "poseidon_hash.json",
    "recursive_verify.json",
    "small_mul.json",
];

const SUBMODULE_TESTDATA_FIXTURES: &[&str] =
    &["gate_ext3_vectors.json", "historical_wire_v2_compact.json"];

#[derive(Clone, Debug, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
struct VpiDescriptor {
    initial_block_number: u64,
    initial_block_chain: Bytes32,
    initial_ext_commitment: Bytes32,
    final_block_number: u64,
    final_block_chain: Bytes32,
    final_ext_commitment: Bytes32,
    prover: Address,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct RegistrationDescriptor {
    channel_id: u32,
    bp_member_slot: u8,
    member_pk_gs: Vec<Bytes32>,
    member_pk_bs: Vec<Bytes32>,
    regev_pk_digests: Vec<Bytes32>,
    recipients: Vec<Address>,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct DepositDescriptor {
    depositor: Address,
    recipient: Bytes32,
    token_index: u32,
    amount: U256,
    aux_data: Bytes32,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct BlockDescriptor {
    channel_id: u32,
    timestamp: u64,
    tx_tree_root: Bytes32,
    key_ids: Vec<u32>,
    block_number: u64,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct LifecycleDescriptor {
    genesis_state_root: Bytes32,
    final_state_root: Bytes32,
    registration: RegistrationDescriptor,
    deposit: DepositDescriptor,
    blocks: Vec<BlockDescriptor>,
    vpis: VpiDescriptor,
    proof_hash: Bytes32,
    proof_length: u32,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct C2cLifecycleDescriptor {
    genesis_state_root: Bytes32,
    final_state_root: Bytes32,
    registration1: RegistrationDescriptor,
    registration2: RegistrationDescriptor,
    deposit: DepositDescriptor,
    blocks: Vec<BlockDescriptor>,
    vpis: VpiDescriptor,
    proof_hash: Bytes32,
    proof_length: u32,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct WithdrawalDescriptor {
    recipient: Address,
    token_index: u32,
    amount: U256,
    nullifier: Bytes32,
    aux_data: Bytes32,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct PayoutDescriptor {
    withdrawals: Vec<WithdrawalDescriptor>,
    withdrawal_prover: Address,
    block_number: u64,
    ext_commitment: Bytes32,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct StandaloneBlockDescriptor {
    channel_id: u32,
    timestamp: u64,
    tx_tree_root: Bytes32,
    key_ids: Vec<u32>,
    block_deposit_hash_chain: Bytes32,
    block_channel_reg_hash_chain: Bytes32,
    genesis_state_root: Bytes32,
    final_state_root: Bytes32,
    initial_block_number: u64,
    final_block_number: u64,
    initial_block_chain: Bytes32,
    final_block_chain: Bytes32,
    proof_hash: Bytes32,
    proof_length: u32,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct CloseIntentDescriptor {
    channel_id: u32,
    close_nonce: u64,
    final_epoch: u64,
    final_small_block_number: u64,
    close_freeze_nonce: u64,
    final_channel_state_digest: Bytes32,
    final_balance_state_h1: Bytes32,
    channel_fund_amount: U256,
    channel_fund_intmax_state_root: Bytes32,
    burn_tx_hash: Bytes32,
    close_withdrawal_digest: Bytes32,
    snapshot_medium_block_number: u64,
    final_state_version: u64,
    final_settled_tx_chain: Bytes32,
    final_settled_tx_accumulator_root: Bytes32,
    close_intent_digest: Bytes32,
    member_set_commitment: Bytes32,
    member_count: u8,
    delegate_count: u16,
    member_pk_gs: Vec<Bytes32>,
    channel_fund_amounts: Vec<U256>,
    token_registry: Vec<u32>,
    token_count: u8,
    token_funds_digest: Bytes32,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct WithdrawalClaimDescriptor {
    channel_id: u32,
    close_intent_digest: Bytes32,
    final_balance_state_h1: Bytes32,
    member_pk_g: Bytes32,
    recipient: Address,
    user_amount_digest: Bytes32,
    withdrawal_nullifier: Bytes32,
    amount: u64,
    token_slot: u8,
    token_index: u32,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct PostCloseClaimDescriptor {
    receiver_channel_id: u32,
    close_intent_digest: Bytes32,
    incoming_tx_hash: Bytes32,
    receiver_pk_g: Bytes32,
    recipient: Address,
    shared_native_nullifier: Bytes32,
    amount: u64,
    token_index: u32,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct CancelCloseDescriptor {
    channel_id: u32,
    close_intent_digest: Bytes32,
    member_set_commitment: Bytes32,
    close_final_state_version: u64,
    revived_state_version: u64,
    revived_channel_state_digest: Bytes32,
    member_pk_gs: Vec<Bytes32>,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct PartialWithdrawalRegistrationDescriptor {
    active_delegate_count: u16,
    bp_member_slot: u8,
    channel_id: u32,
    member_count: u8,
    member_pk_bs: Vec<Bytes32>,
    member_pk_gs: Vec<Bytes32>,
    recipients: Vec<Address>,
    reg_delegate_count: u16,
    regev_pk_digests: Vec<Bytes32>,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct PartialWithdrawalSubmitDescriptor {
    manager: Address,
    verifier: Address,
    close_nonce: u64,
    final_epoch: u64,
    final_small_block_number: u64,
    close_freeze_nonce: u64,
    final_channel_state_digest: Bytes32,
    final_balance_state_h1: Bytes32,
    channel_fund_amounts: Vec<U256>,
    token_registry: Vec<u32>,
    token_count: u8,
    channel_fund_intmax_state_root: Bytes32,
    burn_tx_hash: Bytes32,
    close_withdrawal_digest: Bytes32,
    snapshot_medium_block_number: u64,
    final_state_version: u64,
    final_settled_tx_chain: Bytes32,
    final_settled_tx_acc_root: Bytes32,
    prev_settled_tx_chain: Bytes32,
    withdrawal_recipient: Address,
    withdrawal_token_index: u32,
    withdrawal_amount: u64,
    withdrawal_nullifier: Bytes32,
    withdrawal_aux_data: Bytes32,
    withdrawal_base_nonce: u64,
    burn_tx_leaf: Bytes32,
}

#[derive(Debug)]
struct CohortSets {
    configs: BTreeSet<String>,
    full_proofs: BTreeSet<String>,
    companions: BTreeSet<String>,
}

fn insert_unique(
    set: &mut BTreeSet<String>,
    name: &str,
    invocation: &str,
    class: &str,
) -> Result<(), String> {
    if !set.insert(name.to_owned()) {
        return Err(format!(
            "{name} is owned more than once in the {class} manifest (second owner: {invocation})"
        ));
    }
    Ok(())
}

fn generator_cohort_sets() -> Result<CohortSets, String> {
    let mut sets = CohortSets {
        configs: BTreeSet::new(),
        full_proofs: BTreeSet::new(),
        companions: BTreeSet::new(),
    };
    for cohort in GENERATOR_COHORTS {
        for name in cohort.configs {
            insert_unique(&mut sets.configs, name, cohort.invocation, "config")?;
        }
        for name in cohort.full_proofs {
            insert_unique(&mut sets.full_proofs, name, cohort.invocation, "full proof")?;
        }
        for name in cohort.companions {
            insert_unique(&mut sets.companions, name, cohort.invocation, "companion")?;
        }
    }

    for name in &sets.configs {
        if sets.full_proofs.contains(name) || sets.companions.contains(name) {
            return Err(format!("{name} appears in multiple artifact classes"));
        }
    }
    for name in &sets.full_proofs {
        if sets.companions.contains(name) {
            return Err(format!("{name} appears in multiple artifact classes"));
        }
    }
    Ok(sets)
}

fn exact_set(
    actual: &BTreeSet<String>,
    expected: &BTreeSet<String>,
    label: &str,
) -> Result<(), String> {
    let missing = expected.difference(actual).cloned().collect::<Vec<_>>();
    let extra = actual.difference(expected).cloned().collect::<Vec<_>>();
    if missing.is_empty() && extra.is_empty() {
        Ok(())
    } else {
        Err(format!(
            "{label} mismatch; missing={missing:?}, unexpected={extra:?}"
        ))
    }
}

fn regular_file_names(path: &std::path::Path) -> Result<BTreeSet<String>, String> {
    fs::read_dir(path)
        .map_err(|error| format!("cannot read {}: {error}", path.display()))?
        .map(|entry| {
            let entry = entry.map_err(|error| format!("cannot read directory entry: {error}"))?;
            if !entry
                .file_type()
                .map_err(|error| format!("cannot inspect {}: {error}", entry.path().display()))?
                .is_file()
            {
                return Err(format!(
                    "unexpected non-file artifact in tracked directory: {}",
                    entry.path().display()
                ));
            }
            entry
                .file_name()
                .into_string()
                .map_err(|_| format!("non-UTF-8 artifact name in {}", path.display()))
        })
        .collect()
}

fn json_value(name: &str) -> Result<serde_json::Value, String> {
    serde_json::from_str(&read(name)).map_err(|e| format!("{name}: invalid JSON: {e}"))
}

fn strict_value<T: serde::de::DeserializeOwned>(
    name: &str,
    value: &serde_json::Value,
) -> Result<T, String> {
    serde_json::from_value(value.clone())
        .map_err(|e| format!("{name}: strict companion schema mismatch: {e}"))
}

fn nonzero_address(value: Address, what: &str) -> Result<(), String> {
    if value == Address::default() {
        Err(format!("{what} must not be the zero address"))
    } else {
        Ok(())
    }
}

fn nonzero_word(value: Bytes32, what: &str) -> Result<(), String> {
    if value == Bytes32::default() {
        Err(format!("{what} must not be zero"))
    } else {
        Ok(())
    }
}

fn validate_registration(value: &RegistrationDescriptor, what: &str) -> Result<(), String> {
    let count = value.member_pk_gs.len();
    if count == 0 || count > MAX_SIG_CLUSTER {
        return Err(format!(
            "{what}.member_pk_gs length {count} is outside 1..={MAX_SIG_CLUSTER}"
        ));
    }
    for (field, actual) in [
        ("member_pk_bs", value.member_pk_bs.len()),
        ("regev_pk_digests", value.regev_pk_digests.len()),
        ("recipients", value.recipients.len()),
    ] {
        if actual != count {
            return Err(format!(
                "{what}.{field} length {actual} != member_pk_gs length {count}"
            ));
        }
    }
    if usize::from(value.bp_member_slot) >= count {
        return Err(format!("{what}.bp_member_slot is outside the active set"));
    }
    if value.channel_id == 0 {
        return Err(format!("{what}.channel_id must be nonzero"));
    }
    for (i, recipient) in value.recipients.iter().copied().enumerate() {
        nonzero_address(recipient, &format!("{what}.recipients[{i}]"))?;
    }
    Ok(())
}

fn validate_deposit(value: &DepositDescriptor, what: &str) -> Result<(), String> {
    nonzero_address(value.depositor, &format!("{what}.depositor"))?;
    nonzero_word(value.recipient, &format!("{what}.recipient"))?;
    if value.amount == U256::zero() {
        return Err(format!("{what}.amount must be nonzero"));
    }
    // Token zero and zero aux-data are canonical for the native fixture and intentionally valid.
    let _ = (value.token_index, value.aux_data);
    Ok(())
}

fn validate_blocks(values: &[BlockDescriptor], what: &str) -> Result<(), String> {
    if values.is_empty() {
        return Err(format!("{what}.blocks must not be empty"));
    }
    for (i, block) in values.iter().enumerate() {
        let expected_number = u64::try_from(i + 1).expect("fixture block count fits u64");
        if block.block_number != expected_number {
            return Err(format!(
                "{what}.blocks[{i}].block_number {} != contiguous {expected_number}",
                block.block_number
            ));
        }
        if block.key_ids.is_empty() {
            return Err(format!("{what}.blocks[{i}].key_ids must not be empty"));
        }
        let _ = (block.channel_id, block.timestamp, block.tx_tree_root);
    }
    Ok(())
}

fn validate_vpi_shape(value: &VpiDescriptor, what: &str) -> Result<(), String> {
    if value.final_block_number <= value.initial_block_number {
        return Err(format!("{what}: final block must advance"));
    }
    nonzero_word(
        value.initial_ext_commitment,
        &format!("{what}.initial_ext_commitment"),
    )?;
    nonzero_word(
        value.final_ext_commitment,
        &format!("{what}.final_ext_commitment"),
    )?;
    Ok(())
}

fn validate_lifecycle_shape(value: &LifecycleDescriptor, what: &str) -> Result<(), String> {
    validate_registration(&value.registration, &format!("{what}.registration"))?;
    validate_deposit(&value.deposit, &format!("{what}.deposit"))?;
    validate_blocks(&value.blocks, what)?;
    validate_vpi_shape(&value.vpis, &format!("{what}.vpis"))?;
    if value.genesis_state_root != value.vpis.initial_ext_commitment
        || value.final_state_root != value.vpis.final_ext_commitment
    {
        return Err(format!(
            "{what}: lifecycle roots do not equal the validity initial/final commitments"
        ));
    }
    if value.blocks.last().expect("nonempty").block_number != value.vpis.final_block_number {
        return Err(format!(
            "{what}: last block number does not equal validity final block"
        ));
    }
    nonzero_word(value.proof_hash, &format!("{what}.proof_hash"))?;
    if value.proof_length == 0 {
        return Err(format!("{what}.proof_length must be nonzero"));
    }
    Ok(())
}

fn validate_c2c_lifecycle_shape(value: &C2cLifecycleDescriptor, what: &str) -> Result<(), String> {
    validate_registration(&value.registration1, &format!("{what}.registration1"))?;
    validate_registration(&value.registration2, &format!("{what}.registration2"))?;
    if value.registration1.channel_id == value.registration2.channel_id {
        return Err(format!("{what}: the two registrations alias one channel"));
    }
    validate_deposit(&value.deposit, &format!("{what}.deposit"))?;
    validate_blocks(&value.blocks, what)?;
    validate_vpi_shape(&value.vpis, &format!("{what}.vpis"))?;
    if value.genesis_state_root != value.vpis.initial_ext_commitment
        || value.final_state_root != value.vpis.final_ext_commitment
    {
        return Err(format!(
            "{what}: lifecycle roots do not equal the validity initial/final commitments"
        ));
    }
    if value.blocks.last().expect("nonempty").block_number != value.vpis.final_block_number {
        return Err(format!(
            "{what}: last block number does not equal validity final block"
        ));
    }
    nonzero_word(value.proof_hash, &format!("{what}.proof_hash"))?;
    if value.proof_length == 0 {
        return Err(format!("{what}.proof_length must be nonzero"));
    }
    Ok(())
}

fn validate_payout_shape(value: &PayoutDescriptor, what: &str) -> Result<(), String> {
    if value.withdrawals.len() != 1 {
        return Err(format!(
            "{what}.withdrawals must contain the generator's exact one-withdrawal cohort"
        ));
    }
    nonzero_address(
        value.withdrawal_prover,
        &format!("{what}.withdrawal_prover"),
    )?;
    nonzero_word(value.ext_commitment, &format!("{what}.ext_commitment"))?;
    for (i, withdrawal) in value.withdrawals.iter().enumerate() {
        nonzero_address(
            withdrawal.recipient,
            &format!("{what}.withdrawals[{i}].recipient"),
        )?;
        nonzero_word(
            withdrawal.nullifier,
            &format!("{what}.withdrawals[{i}].nullifier"),
        )?;
        if withdrawal.amount == U256::zero() {
            return Err(format!("{what}.withdrawals[{i}].amount must be nonzero"));
        }
        let _ = (withdrawal.token_index, withdrawal.aux_data);
    }
    Ok(())
}

fn validate_companion_schema(name: &str, value: &serde_json::Value) -> Result<(), String> {
    match name {
        "vpi_fixture.json" => {
            let parsed: VpiDescriptor = strict_value(name, value)?;
            validate_vpi_shape(&parsed, name)
        }
        "block_fixture.json" => {
            let parsed: StandaloneBlockDescriptor = strict_value(name, value)?;
            nonzero_word(
                parsed.genesis_state_root,
                "block_fixture.genesis_state_root",
            )?;
            nonzero_word(parsed.final_state_root, "block_fixture.final_state_root")?;
            nonzero_word(parsed.proof_hash, "block_fixture.proof_hash")?;
            if parsed.proof_length == 0
                || parsed.final_block_number <= parsed.initial_block_number
                || parsed.key_ids.is_empty()
            {
                return Err("block_fixture.json: invalid block/proof dimensions".to_owned());
            }
            let _ = (
                parsed.channel_id,
                parsed.timestamp,
                parsed.tx_tree_root,
                parsed.block_deposit_hash_chain,
                parsed.block_channel_reg_hash_chain,
                parsed.initial_block_chain,
                parsed.final_block_chain,
            );
            Ok(())
        }
        "lifecycle.json"
        | "close_lifecycle.json"
        | "sepolia_lifecycle.json"
        | "burn_lifecycle.json" => {
            let parsed: LifecycleDescriptor = strict_value(name, value)?;
            validate_lifecycle_shape(&parsed, name)
        }
        "c2c_lifecycle.json" => {
            let parsed: C2cLifecycleDescriptor = strict_value(name, value)?;
            validate_c2c_lifecycle_shape(&parsed, name)
        }
        "withdrawal_payout.json"
        | "close_withdrawal_payout.json"
        | "sepolia_withdrawal_payout.json"
        | "burn_withdrawal_payout.json"
        | "c2c_withdrawal_payout.json" => {
            let parsed: PayoutDescriptor = strict_value(name, value)?;
            validate_payout_shape(&parsed, name)
        }
        "close_intent.json" => {
            let parsed: CloseIntentDescriptor = strict_value(name, value)?;
            if parsed.member_pk_gs.is_empty()
                || parsed.channel_fund_amounts.len() != MAX_CHANNEL_TOKENS
                || parsed.token_registry.len() != MAX_CHANNEL_TOKENS
                || parsed.token_count == 0
                || usize::from(parsed.token_count) > MAX_CHANNEL_TOKENS
            {
                return Err("close_intent.json: invalid fixed-width companion arrays".to_owned());
            }
            Ok(())
        }
        "withdrawal_claim.json" => {
            let parsed: WithdrawalClaimDescriptor = strict_value(name, value)?;
            nonzero_address(parsed.recipient, "withdrawal_claim.recipient")?;
            nonzero_word(
                parsed.withdrawal_nullifier,
                "withdrawal_claim.withdrawal_nullifier",
            )
        }
        "post_close_claim.json" => {
            let parsed: PostCloseClaimDescriptor = strict_value(name, value)?;
            nonzero_address(parsed.recipient, "post_close_claim.recipient")?;
            nonzero_word(
                parsed.shared_native_nullifier,
                "post_close_claim.shared_native_nullifier",
            )
        }
        "cancel_close.json" => {
            let parsed: CancelCloseDescriptor = strict_value(name, value)?;
            if parsed.member_pk_gs.is_empty() || parsed.member_pk_gs.len() > MAX_SIG_CLUSTER {
                return Err("cancel_close.json: invalid member_pk_gs length".to_owned());
            }
            Ok(())
        }
        "pw_reg.json" => {
            let parsed: PartialWithdrawalRegistrationDescriptor = strict_value(name, value)?;
            let count = usize::from(parsed.member_count);
            if count == 0
                || count > MAX_SIG_CLUSTER
                || parsed.member_pk_gs.len() != count
                || parsed.member_pk_bs.len() != count
                || parsed.regev_pk_digests.len() != count
                || parsed.recipients.len() != count
                || usize::from(parsed.bp_member_slot) >= count
            {
                return Err("pw_reg.json: inconsistent active member arrays/count".to_owned());
            }
            for (i, recipient) in parsed.recipients.iter().copied().enumerate() {
                nonzero_address(recipient, &format!("pw_reg.recipients[{i}]"))?;
            }
            Ok(())
        }
        "pw_submit.json" => {
            let parsed: PartialWithdrawalSubmitDescriptor = strict_value(name, value)?;
            nonzero_address(parsed.manager, "pw_submit.manager")?;
            nonzero_address(parsed.verifier, "pw_submit.verifier")?;
            nonzero_address(
                parsed.withdrawal_recipient,
                "pw_submit.withdrawal_recipient",
            )?;
            if parsed.channel_fund_amounts.len() != MAX_CHANNEL_TOKENS
                || parsed.token_registry.len() != MAX_CHANNEL_TOKENS
                || parsed.token_count == 0
                || usize::from(parsed.token_count) > MAX_CHANNEL_TOKENS
            {
                return Err("pw_submit.json: invalid fixed-width token arrays".to_owned());
            }
            Ok(())
        }
        "close_asset_backing_public_inputs.json" => {
            let limbs: Vec<u64> = strict_value(name, value)?;
            if limbs.len() != CLOSE_ASSET_BACKING_PUBLIC_INPUTS_LEN {
                return Err(format!(
                    "{name}: expected {CLOSE_ASSET_BACKING_PUBLIC_INPUTS_LEN} raw limbs"
                ));
            }
            CloseAssetBackingPublicInputs::from_u64_slice(&limbs).map_err(|e| e.to_string())?;
            // The bare limb file is a redundant view of the proof's own public inputs.
            require_equal(
                &limbs,
                &parse_full_public_inputs("close_asset_backing_mle.json")?,
                "close_asset_backing_public_inputs vs close_asset_backing_mle.proof.publicInputs",
            )
        }
        "close_asset_backing_manifest.json" => {
            let parsed: BackingFixtureManifest = strict_value(name, value)?;
            require_equal(
                &parsed.schema_version,
                &PUBLIC_CLOSE_BUNDLE_SCHEMA_VERSION,
                "close_asset_backing_manifest.schemaVersion",
            )?;
            require_equal(
                &parsed.backing_public_input_count,
                &CLOSE_ASSET_BACKING_PUBLIC_INPUTS_LEN,
                "close_asset_backing_manifest.backingPublicInputCount",
            )?;
            // The manifest authenticates exactly the three checked-in backing artifacts (the same
            // reader `DeployCloseCli._readBackingMle` uses for a live bundle).
            for (file, bytes, sha) in [
                (
                    "close_asset_backing_mle.json",
                    Some(parsed.backing_mle_bytes),
                    &parsed.backing_mle_sha256,
                ),
                (
                    "close_asset_backing_mle_config.json",
                    Some(parsed.backing_mle_config_bytes),
                    &parsed.backing_mle_config_sha256,
                ),
                // The limb file carries no byte count in the manifest, only its digest.
                (
                    "close_asset_backing_public_inputs.json",
                    None,
                    &parsed.backing_public_inputs_sha256,
                ),
            ] {
                let content = read(file);
                if let Some(bytes) = bytes {
                    require_equal(&content.len(), &bytes, &format!("{name}: {file} byte length"))?;
                }
                let digest = format!("0x{}", hex::encode(Sha256::digest(content.as_bytes())));
                require_equal(&digest, sha, &format!("{name}: {file} sha256"))?;
            }
            let public_inputs = CloseAssetBackingPublicInputs::from_u64_slice(
                &parse_full_public_inputs("close_asset_backing_mle.json")?,
            )
            .map_err(|e| e.to_string())?;
            require_equal(
                &public_inputs.anchor_block_number.as_u64(),
                &parsed.backing_anchor_block_number,
                "close_asset_backing_manifest.backingAnchorBlockNumber",
            )?;
            require_equal(
                &public_inputs.finalized_extended_state_commitment,
                &parsed.backing_finalized_extended_state_commitment,
                "close_asset_backing_manifest.backingFinalizedExtendedStateCommitment",
            )
        }
        _ => Err(format!("{name}: no strict companion schema is registered")),
    }
}

/// `close_asset_backing_manifest.json`: the `public_close_prover` bundle manifest shape written by
/// the close-family co-generator (`generate_close_fixture`), plus its leading `_comment`.
#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct BackingFixtureManifest {
    #[serde(rename = "_comment")]
    _comment: String,
    schema_version: u32,
    chain_id: u64,
    rollup: String,
    channel_id: u64,
    balance_verifier_data_sha256: String,
    close_proof_file: String,
    close_proof_bytes: usize,
    close_mle_file: String,
    close_mle_bytes: usize,
    backing_proof_file: String,
    backing_proof_bytes: usize,
    backing_mle_file: String,
    backing_mle_bytes: usize,
    backing_mle_config_file: String,
    backing_mle_config_bytes: usize,
    backing_public_inputs_file: String,
    backing_public_input_count: usize,
    backing_finalized_extended_state_commitment: Bytes32,
    backing_anchor_block_number: u64,
    close_intent_file: String,
    close_intent_full_file: String,
    close_public_inputs_file: String,
    close_public_input_count: usize,
    close_proof_sha256: String,
    close_mle_sha256: String,
    backing_proof_sha256: String,
    backing_mle_sha256: String,
    backing_mle_config_sha256: String,
    backing_public_inputs_sha256: String,
    close_intent_sha256: String,
    close_intent_full_sha256: String,
    close_public_inputs_sha256: String,
    key_material_consumed: bool,
    self_verified: bool,
}

fn parse_full_public_inputs(name: &str) -> Result<Vec<u64>, String> {
    // Artifact-class/schema/config/compact integrity is enforced independently by
    // `tracked_live_full_v2_fixtures_are_exhaustive_and_match_configs`. Read just this redundant
    // view here so companion relationship failures remain visible even during an intentional
    // wire-generation cutover, instead of being masked by the first stale full-proof schema.
    json_value(name)?
        .pointer("/proof/publicInputs")
        .and_then(serde_json::Value::as_array)
        .ok_or_else(|| format!("{name}: missing proof.publicInputs array"))?
        .iter()
        .enumerate()
        .map(|(i, value)| {
            let encoded = value
                .as_str()
                .ok_or_else(|| format!("{name}: publicInputs[{i}] must be a hex string"))?;
            let hex = encoded
                .strip_prefix("0x")
                .ok_or_else(|| format!("{name}: publicInputs[{i}] lacks canonical 0x prefix"))?;
            if hex.len() != 16 || hex.bytes().any(|b| b.is_ascii_uppercase()) {
                return Err(format!(
                    "{name}: publicInputs[{i}] is not canonical fixed-width lowercase hex"
                ));
            }
            u64::from_str_radix(hex, 16)
                .map_err(|e| format!("{name}: publicInputs[{i}] is not canonical u64: {e}"))
        })
        .collect()
}

fn require_equal<T: PartialEq + std::fmt::Debug>(
    actual: &T,
    expected: &T,
    what: &str,
) -> Result<(), String> {
    if actual == expected {
        Ok(())
    } else {
        Err(format!(
            "{what} mismatch: actual={actual:?}, expected={expected:?}"
        ))
    }
}

fn validity_public_inputs(value: &VpiDescriptor) -> Result<ValidityPublicInputs, String> {
    Ok(ValidityPublicInputs {
        initial_block_number: BlockNumber::new(value.initial_block_number)
            .map_err(|e| e.to_string())?,
        initial_block_chain: value.initial_block_chain,
        initial_ext_commitment: value.initial_ext_commitment,
        final_block_number: BlockNumber::new(value.final_block_number)
            .map_err(|e| e.to_string())?,
        final_block_chain: value.final_block_chain,
        final_ext_commitment: value.final_ext_commitment,
        prover: value.prover,
    })
}

fn validate_validity_proof_binding(value: &VpiDescriptor, full_name: &str) -> Result<(), String> {
    let actual = parse_full_public_inputs(full_name)?;
    let expected = validity_public_inputs(value)?.hash().to_u64_vec();
    require_equal(
        &actual,
        &expected,
        &format!("{full_name} validity public-input hash"),
    )
}

fn validate_withdrawal_proof_binding(
    payout: &PayoutDescriptor,
    full_name: &str,
) -> Result<(), String> {
    let mut withdrawal_hash = Bytes32::default();
    for withdrawal in &payout.withdrawals {
        withdrawal_hash = Withdrawal {
            recipient: withdrawal.recipient,
            token_index: withdrawal.token_index,
            amount: withdrawal.amount,
            nullifier: withdrawal.nullifier,
            aux_data: withdrawal.aux_data,
        }
        .hash_with_prev_hash(withdrawal_hash);
    }
    let block_number = BlockNumber::new(payout.block_number).map_err(|e| e.to_string())?;
    let inputs = WithdrawalProofPublicInputs {
        withdrawal_hash,
        withdrawal_prover: payout.withdrawal_prover,
        ext_public_state_commitment: payout.ext_commitment,
        block_number,
    };
    let expected = [
        inputs.hash().to_u64_vec(),
        inputs.ext_public_state_commitment.to_u64_vec(),
        inputs.block_number.to_u64_vec(),
    ]
    .concat();
    let actual = parse_full_public_inputs(full_name)?;
    require_equal(
        &actual,
        &expected,
        &format!("{full_name} withdrawal public inputs"),
    )
}

fn padded_member_commitment(member_pk_gs: &[Bytes32]) -> Result<Bytes32, String> {
    if member_pk_gs.is_empty() || member_pk_gs.len() > MAX_SIG_CLUSTER {
        return Err(format!(
            "member count {} is outside 1..={MAX_SIG_CLUSTER}",
            member_pk_gs.len()
        ));
    }
    let mut padded = [Bytes32::default(); MAX_SIG_CLUSTER];
    padded[..member_pk_gs.len()].copy_from_slice(member_pk_gs);
    Ok(close_member_set_commitment(
        &padded,
        u8::try_from(member_pk_gs.len()).expect("bounded member count"),
    ))
}

fn fixed_token_vectors(
    registry: &[u32],
    amounts: &[U256],
    what: &str,
) -> Result<([u32; MAX_CHANNEL_TOKENS], [U256; MAX_CHANNEL_TOKENS]), String> {
    let registry: [u32; MAX_CHANNEL_TOKENS] = registry.try_into().map_err(|_| {
        format!("{what}.token_registry must have exactly {MAX_CHANNEL_TOKENS} entries")
    })?;
    let amounts: [U256; MAX_CHANNEL_TOKENS] = amounts.try_into().map_err(|_| {
        format!("{what}.channel_fund_amounts must have exactly {MAX_CHANNEL_TOKENS} entries")
    })?;
    Ok((registry, amounts))
}

#[test]
fn generator_owned_json_cohort_is_exact_and_companion_schemas_are_strict() {
    let sets = generator_cohort_sets().expect("valid generator ownership manifest");
    assert_eq!(sets.configs.len(), 16, "config cohort count drift");
    assert_eq!(sets.full_proofs.len(), 17, "full-proof cohort count drift");
    assert_eq!(sets.companions.len(), 20, "companion cohort count drift");
    assert_eq!(
        sets.configs.len() + sets.full_proofs.len() + sets.companions.len(),
        53,
        "atomic generator-owned JSON cohort count drift"
    );

    let expected_configs = LIVE_CONFIG_COHORT
        .iter()
        .map(|name| (*name).to_owned())
        .collect::<BTreeSet<_>>();
    exact_set(
        &sets.configs,
        &expected_configs,
        "generator config ownership",
    )
    .expect("all configs have one generator owner");
    let expected_full = LIVE_FULL_CONFIG_PAIRS
        .iter()
        .map(|(name, _)| (*name).to_owned())
        .collect::<BTreeSet<_>>();
    exact_set(
        &sets.full_proofs,
        &expected_full,
        "generator full-proof ownership",
    )
    .expect("all full proofs have one generator owner");

    let mut expected_root_json = sets.configs.clone();
    expected_root_json.extend(sets.full_proofs.iter().cloned());
    expected_root_json.extend(sets.companions.iter().cloned());
    for name in INTENTIONAL_NON_COHORT_JSON {
        assert!(
            expected_root_json.insert((*name).to_owned()),
            "intentional non-cohort exception {name} aliases a generated artifact"
        );
    }
    let discovered_root_json = fs::read_dir(data_path("."))
        .expect("read contracts/test/data")
        .map(|entry| entry.expect("read fixture directory entry"))
        .filter(|entry| entry.file_type().expect("fixture file type").is_file())
        .filter_map(|entry| {
            let name = entry.file_name().to_string_lossy().into_owned();
            name.ends_with(".json").then_some(name)
        })
        .collect::<BTreeSet<_>>();
    exact_set(
        &discovered_root_json,
        &expected_root_json,
        "contracts/test/data root JSON release surface",
    )
    .expect("no missing, extra, or stale root JSON artifact");

    for name in &sets.companions {
        let value = json_value(name).unwrap_or_else(|e| panic!("{e}"));
        validate_companion_schema(name, &value).unwrap_or_else(|e| panic!("{e}"));
    }

    let wasm_names = INTENTIONAL_WASM_BINARY_OUTPUTS
        .iter()
        .copied()
        .collect::<BTreeSet<_>>();
    assert_eq!(
        wasm_names.len(),
        INTENTIONAL_WASM_BINARY_OUTPUTS.len(),
        "duplicate intentional WASM binary output"
    );
    assert!(
        INTENTIONAL_WASM_BINARY_OUTPUTS
            .iter()
            .all(|name| name.ends_with(".bin") && !expected_root_json.contains(*name)),
        "WASM binaries must remain outside the JSON cutover cohort"
    );
}

#[test]
fn pinned_submodule_fixture_surfaces_are_exact_and_keep_v1_quarantined() {
    let fixture_dir = repo_root().join("contracts/lib/polygon-plonky2/mle/contracts/test/fixtures");
    let expected_fixtures = SUBMODULE_SOLIDITY_FIXTURES
        .iter()
        .map(|name| (*name).to_owned())
        .collect::<BTreeSet<_>>();
    assert_eq!(
        expected_fixtures.len(),
        SUBMODULE_SOLIDITY_FIXTURES.len(),
        "duplicate pinned submodule Solidity fixture"
    );
    exact_set(
        &regular_file_names(&fixture_dir).expect("read pinned submodule Solidity fixtures"),
        &expected_fixtures,
        "pinned submodule Solidity fixture surface",
    )
    .expect("no missing, extra, or resurrected submodule Solidity fixture");
    assert!(
        !expected_fixtures.contains("xlarge_mul.json"),
        "retired xlarge packed-v1 fixture must stay absent"
    );

    assert_eq!(
        SUBMODULE_PACKED_V1_FIXTURES.len(),
        7,
        "packed-v1 conformance fixture count drift"
    );
    for name in SUBMODULE_PACKED_V1_FIXTURES {
        let path = fixture_dir.join(name);
        let value: serde_json::Value = serde_json::from_str(
            &fs::read_to_string(&path)
                .unwrap_or_else(|error| panic!("cannot read {}: {error}", path.display())),
        )
        .unwrap_or_else(|error| panic!("{} is not JSON: {error}", path.display()));
        assert_eq!(
            value
                .get("protocolVersion")
                .and_then(serde_json::Value::as_u64),
            Some(1),
            "{name} must remain explicitly quarantined as packed-v1 conformance data"
        );
    }

    let testdata_dir = repo_root().join("contracts/lib/polygon-plonky2/mle/testdata");
    let expected_testdata = SUBMODULE_TESTDATA_FIXTURES
        .iter()
        .map(|name| (*name).to_owned())
        .collect::<BTreeSet<_>>();
    exact_set(
        &regular_file_names(&testdata_dir).expect("read pinned submodule testdata fixtures"),
        &expected_testdata,
        "pinned submodule testdata fixture surface",
    )
    .expect("no missing or extra submodule testdata fixture");
}

#[test]
fn cohort_and_schema_helpers_reject_missing_extra_and_mixed_artifacts() {
    let expected = ["a.json", "b.json"]
        .into_iter()
        .map(str::to_owned)
        .collect::<BTreeSet<_>>();
    let missing = ["a.json"]
        .into_iter()
        .map(str::to_owned)
        .collect::<BTreeSet<_>>();
    let extra = ["a.json", "b.json", "stale.json"]
        .into_iter()
        .map(str::to_owned)
        .collect::<BTreeSet<_>>();
    assert!(exact_set(&missing, &expected, "synthetic").is_err());
    assert!(exact_set(&extra, &expected, "synthetic").is_err());

    let lifecycle = json_value("lifecycle.json").expect("fixture JSON");
    let mut with_unknown = lifecycle.clone();
    with_unknown
        .as_object_mut()
        .expect("lifecycle object")
        .insert("stale_generation_tail".to_owned(), serde_json::Value::Null);
    assert!(
        validate_companion_schema("lifecycle.json", &with_unknown).is_err(),
        "an old/new mixed companion tail must fail closed"
    );

    let mut with_missing = lifecycle;
    with_missing
        .as_object_mut()
        .expect("lifecycle object")
        .remove("vpis");
    assert!(
        validate_companion_schema("lifecycle.json", &with_missing).is_err(),
        "a missing companion field must fail closed"
    );

    let config_value = json_value("mle_fixture_config.json").expect("config JSON");
    assert!(
        validate_companion_schema("lifecycle.json", &config_value).is_err(),
        "a proof/config artifact must not be accepted under a companion filename"
    );
}

#[test]
fn release_driver_keeps_foundry_skip_success_fail_closed() {
    let path = repo_root().join(".github/ci/forge-test-guard.sh");
    let guard =
        fs::read_to_string(&path).unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    assert!(
        guard.contains("select(.value.status != \"Success\")"),
        "forge guard must reject Foundry's exit-zero Skipped status"
    );
    assert!(
        guard.contains("test/CloseLifecycleE2E.t.sol:CloseLifecycleE2ETest"),
        "the CREATE2 manager-recipient check must remain a required non-skipping suite"
    );

    let ci_path = repo_root().join(".github/workflows/ci.yml");
    let ci = fs::read_to_string(&ci_path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", ci_path.display()));
    for required in [
        "cache-dependency-path: node/package-lock.json",
        "run: npm ci --ignore-scripts",
        "run: npm test",
    ] {
        assert!(
            ci.contains(required),
            "CI must retain the fail-closed Node proof/config binding gate: {required}"
        );
    }
}

fn validate_standalone_validity_companions() -> Result<(), String> {
    let block: StandaloneBlockDescriptor =
        strict_value("block_fixture.json", &json_value("block_fixture.json")?)?;
    let vpi: VpiDescriptor = strict_value("vpi_fixture.json", &json_value("vpi_fixture.json")?)?;
    validate_companion_schema("block_fixture.json", &json_value("block_fixture.json")?)?;
    validate_companion_schema("vpi_fixture.json", &json_value("vpi_fixture.json")?)?;
    for (actual, expected, field) in [
        (
            block.initial_block_number,
            vpi.initial_block_number,
            "initial_block_number",
        ),
        (
            block.final_block_number,
            vpi.final_block_number,
            "final_block_number",
        ),
    ] {
        require_equal(
            &actual,
            &expected,
            &format!("block_fixture/vpi_fixture {field}"),
        )?;
    }
    for (actual, expected, field) in [
        (
            block.initial_block_chain,
            vpi.initial_block_chain,
            "initial_block_chain",
        ),
        (
            block.final_block_chain,
            vpi.final_block_chain,
            "final_block_chain",
        ),
        (
            block.genesis_state_root,
            vpi.initial_ext_commitment,
            "genesis_state_root",
        ),
        (
            block.final_state_root,
            vpi.final_ext_commitment,
            "final_state_root",
        ),
    ] {
        require_equal(
            &actual,
            &expected,
            &format!("block_fixture/vpi_fixture {field}"),
        )?;
    }
    validate_validity_proof_binding(&vpi, "mle_fixture.json")
}

fn validate_lifecycle_pair(
    lifecycle_name: &str,
    validity_full_name: &str,
    payout_name: &str,
    withdrawal_full_name: &str,
    require_close_family_amounts: bool,
) -> Result<(), String> {
    let lifecycle: LifecycleDescriptor =
        strict_value(lifecycle_name, &json_value(lifecycle_name)?)?;
    let payout: PayoutDescriptor = strict_value(payout_name, &json_value(payout_name)?)?;
    validate_lifecycle_shape(&lifecycle, lifecycle_name)?;
    validate_payout_shape(&payout, payout_name)?;
    validate_validity_proof_binding(&lifecycle.vpis, validity_full_name)?;
    validate_withdrawal_proof_binding(&payout, withdrawal_full_name)?;
    require_equal(
        &payout.block_number,
        &lifecycle.vpis.final_block_number,
        &format!("{payout_name} block_number"),
    )?;
    require_equal(
        &payout.ext_commitment,
        &lifecycle.vpis.final_ext_commitment,
        &format!("{payout_name} ext_commitment"),
    )?;
    let withdrawal = &payout.withdrawals[0];
    if withdrawal.amount > lifecycle.deposit.amount {
        return Err(format!(
            "{payout_name}: withdrawal amount {} exceeds lifecycle deposit {}",
            withdrawal.amount, lifecycle.deposit.amount
        ));
    }
    if require_close_family_amounts {
        // Signer-independent exit: the close intent's fund vector is what REMAINS in the channel
        // after the lifecycle's sole native withdrawal (`deposit - withdrawal`), and
        // `CloseLifecycleE2E` requires the L1 payout pulled by the Manager to equal exactly that
        // materialized amount (`finalizedChannelFundAmount(0) == amounts[0]`). The co-generator
        // therefore fixes `deposit - withdrawal == withdrawal` (6 / 3); a different pair is a
        // stale or hand-edited close family.
        if withdrawal.amount == U256::default() {
            return Err(format!("{payout_name}: the close family needs a nonzero withdrawal"));
        }
        require_equal(
            &(lifecycle.deposit.amount - withdrawal.amount),
            &withdrawal.amount,
            "close_ remaining channel funds (deposit - withdrawal) vs payout",
        )?;
    }
    Ok(())
}

fn validate_c2c_lifecycle_pair() -> Result<(), String> {
    let lifecycle: C2cLifecycleDescriptor =
        strict_value("c2c_lifecycle.json", &json_value("c2c_lifecycle.json")?)?;
    let payout: PayoutDescriptor = strict_value(
        "c2c_withdrawal_payout.json",
        &json_value("c2c_withdrawal_payout.json")?,
    )?;
    validate_c2c_lifecycle_shape(&lifecycle, "c2c_lifecycle.json")?;
    validate_payout_shape(&payout, "c2c_withdrawal_payout.json")?;
    validate_validity_proof_binding(&lifecycle.vpis, "c2c_lifecycle_validity_mle.json")?;
    validate_withdrawal_proof_binding(&payout, "c2c_withdrawal_mle.json")?;
    require_equal(
        &payout.block_number,
        &lifecycle.vpis.final_block_number,
        "c2c payout block_number",
    )?;
    require_equal(
        &payout.ext_commitment,
        &lifecycle.vpis.final_ext_commitment,
        "c2c payout ext_commitment",
    )?;
    if payout.withdrawals[0].amount > lifecycle.deposit.amount {
        return Err("c2c payout exceeds the lifecycle deposit".to_owned());
    }
    Ok(())
}

/// The signer-independent exit cross-bindings `ChannelSettlementManager._checkCloseProof` and
/// `CloseFundingMaterializer` enforce on chain: the close intent's `intmax_state_root` is the
/// `close_` lifecycle's finalized root, and the whole-vector backing statement carries the close
/// intent's exact `(channel, settled_tx_chain, token_funds_digest)` key, that same finalized
/// commitment and the lifecycle's last block as its anchor.
fn validate_close_backing_binding(
    close: &CloseIntentDescriptor,
    close_lifecycle: &LifecycleDescriptor,
) -> Result<(), String> {
    let backing = CloseAssetBackingPublicInputs::from_u64_slice(&parse_full_public_inputs(
        "close_asset_backing_mle.json",
    )?)
    .map_err(|e| e.to_string())?;
    require_equal(
        &close.channel_fund_intmax_state_root,
        &close_lifecycle.final_state_root,
        "close_intent.channel_fund_intmax_state_root vs close_lifecycle.final_state_root",
    )?;
    require_equal(
        &backing.channel_id.channel_id(),
        &close.channel_id,
        "backing.channel_id vs close_intent.channel_id",
    )?;
    require_equal(
        &backing.settled_tx_chain,
        &close.final_settled_tx_chain,
        "backing.settled_tx_chain vs close_intent.final_settled_tx_chain",
    )?;
    require_equal(
        &backing.token_funds_digest,
        &close.token_funds_digest,
        "backing.token_funds_digest vs close_intent.token_funds_digest",
    )?;
    require_equal(
        &backing.finalized_extended_state_commitment,
        &close_lifecycle.final_state_root,
        "backing.finalized_extended_state_commitment vs close_lifecycle.final_state_root",
    )?;
    let last_block = close_lifecycle
        .blocks
        .last()
        .ok_or_else(|| "close_lifecycle.json has no blocks".to_owned())?;
    require_equal(
        &backing.anchor_block_number.as_u64(),
        &last_block.block_number,
        "backing.anchor_block_number vs close_lifecycle last block",
    )
}

fn validate_close_intent_binding() -> Result<CloseIntentDescriptor, String> {
    let descriptor: CloseIntentDescriptor =
        strict_value("close_intent.json", &json_value("close_intent.json")?)?;
    let public_inputs = ChannelClosePublicInputs::from_u64_slice(&parse_full_public_inputs(
        "close_intent_mle.json",
    )?)
    .map_err(|e| e.to_string())?;

    require_equal(
        &public_inputs.channel_id.channel_id(),
        &descriptor.channel_id,
        "close_intent.channel_id",
    )?;
    require_equal(
        &public_inputs.close_nonce,
        &descriptor.close_nonce,
        "close_intent.close_nonce",
    )?;
    require_equal(
        &public_inputs.final_epoch,
        &descriptor.final_epoch,
        "close_intent.final_epoch",
    )?;
    require_equal(
        &public_inputs.final_small_block_number,
        &descriptor.final_small_block_number,
        "close_intent.final_small_block_number",
    )?;
    require_equal(
        &public_inputs.close_freeze_nonce,
        &descriptor.close_freeze_nonce,
        "close_intent.close_freeze_nonce",
    )?;
    require_equal(
        &public_inputs.final_channel_state_digest,
        &descriptor.final_channel_state_digest,
        "close_intent.final_channel_state_digest",
    )?;
    require_equal(
        &public_inputs.final_balance_state_h1,
        &descriptor.final_balance_state_h1,
        "close_intent.final_balance_state_h1",
    )?;
    require_equal(
        &public_inputs.channel_fund_amount,
        &descriptor.channel_fund_amount,
        "close_intent.channel_fund_amount",
    )?;
    require_equal(
        &public_inputs.channel_fund_intmax_state_root,
        &descriptor.channel_fund_intmax_state_root,
        "close_intent.channel_fund_intmax_state_root",
    )?;
    require_equal(
        &public_inputs.burn_tx_hash,
        &descriptor.burn_tx_hash,
        "close_intent.burn_tx_hash",
    )?;
    require_equal(
        &public_inputs.close_withdrawal_digest,
        &descriptor.close_withdrawal_digest,
        "close_intent.close_withdrawal_digest",
    )?;
    require_equal(
        &public_inputs.close_intent_digest,
        &descriptor.close_intent_digest,
        "close_intent.close_intent_digest",
    )?;
    require_equal(
        &public_inputs.snapshot_medium_block_number,
        &descriptor.snapshot_medium_block_number,
        "close_intent.snapshot_medium_block_number",
    )?;
    require_equal(
        &public_inputs.final_state_version,
        &descriptor.final_state_version,
        "close_intent.final_state_version",
    )?;
    require_equal(
        &public_inputs.final_settled_tx_chain,
        &descriptor.final_settled_tx_chain,
        "close_intent.final_settled_tx_chain",
    )?;
    require_equal(
        &public_inputs.final_settled_tx_accumulator_root,
        &descriptor.final_settled_tx_accumulator_root,
        "close_intent.final_settled_tx_accumulator_root",
    )?;
    require_equal(
        &public_inputs.member_set_commitment,
        &descriptor.member_set_commitment,
        "close_intent.member_set_commitment",
    )?;
    require_equal(
        &public_inputs.member_count,
        &descriptor.member_count,
        "close_intent.member_count",
    )?;
    require_equal(
        &public_inputs.delegate_count,
        &descriptor.delegate_count,
        "close_intent.delegate_count",
    )?;
    require_equal(
        &public_inputs.token_funds_digest,
        &descriptor.token_funds_digest,
        "close_intent.token_funds_digest",
    )?;

    if descriptor.member_pk_gs.len() != usize::from(descriptor.member_count) {
        return Err("close_intent member_count does not match member_pk_gs".to_owned());
    }
    let expected_member_set = padded_member_commitment(&descriptor.member_pk_gs)?;
    require_equal(
        &descriptor.member_set_commitment,
        &expected_member_set,
        "close_intent recomputed member_set_commitment",
    )?;
    let (registry, amounts) = fixed_token_vectors(
        &descriptor.token_registry,
        &descriptor.channel_fund_amounts,
        "close_intent",
    )?;
    if descriptor.token_count == 0 || usize::from(descriptor.token_count) > MAX_CHANNEL_TOKENS {
        return Err("close_intent token_count is outside the fixed-width registry".to_owned());
    }
    require_equal(
        &descriptor.channel_fund_amount,
        &amounts[0],
        "close_intent native scalar/amounts[0]",
    )?;
    require_equal(
        &descriptor.token_funds_digest,
        &token_funds_digest(&registry, descriptor.token_count, &amounts),
        "close_intent recomputed token_funds_digest",
    )?;
    for slot in usize::from(descriptor.token_count)..MAX_CHANNEL_TOKENS {
        if registry[slot] != 0 || amounts[slot] != U256::zero() {
            return Err(format!(
                "close_intent inactive token slot {slot} is not canonically zero"
            ));
        }
    }
    Ok(descriptor)
}

fn validate_withdrawal_claim_binding() -> Result<(), String> {
    let descriptor: WithdrawalClaimDescriptor = strict_value(
        "withdrawal_claim.json",
        &json_value("withdrawal_claim.json")?,
    )?;
    let public_inputs = WithdrawalClaimPublicInputs::from_u64_slice(&parse_full_public_inputs(
        "withdrawal_claim_mle.json",
    )?)?;
    require_equal(
        &public_inputs.channel_id.channel_id(),
        &descriptor.channel_id,
        "withdrawal_claim.channel_id",
    )?;
    require_equal(
        &public_inputs.close_intent_digest,
        &descriptor.close_intent_digest,
        "withdrawal_claim.close_intent_digest",
    )?;
    require_equal(
        &public_inputs.final_balance_state_h1,
        &descriptor.final_balance_state_h1,
        "withdrawal_claim.final_balance_state_h1",
    )?;
    require_equal(
        &public_inputs.member_pk_g,
        &descriptor.member_pk_g,
        "withdrawal_claim.member_pk_g",
    )?;
    require_equal(
        &public_inputs.recipient,
        &descriptor.recipient,
        "withdrawal_claim.recipient",
    )?;
    require_equal(
        &public_inputs.user_amount_digest,
        &descriptor.user_amount_digest,
        "withdrawal_claim.user_amount_digest",
    )?;
    require_equal(
        &public_inputs.withdrawal_nullifier,
        &descriptor.withdrawal_nullifier,
        "withdrawal_claim.withdrawal_nullifier",
    )?;
    require_equal(
        &public_inputs.amount,
        &descriptor.amount,
        "withdrawal_claim.amount",
    )?;
    require_equal(
        &public_inputs.token_slot,
        &descriptor.token_slot,
        "withdrawal_claim.token_slot",
    )?;
    require_equal(
        &public_inputs.token_index,
        &descriptor.token_index,
        "withdrawal_claim.token_index",
    )
}

fn validate_post_close_claim_binding() -> Result<(), String> {
    let descriptor: PostCloseClaimDescriptor = strict_value(
        "post_close_claim.json",
        &json_value("post_close_claim.json")?,
    )?;
    let public_inputs = PostCloseClaimPublicInputs::from_u64_slice(&parse_full_public_inputs(
        "post_close_claim_mle.json",
    )?)?;
    require_equal(
        &public_inputs.receiver_channel_id.channel_id(),
        &descriptor.receiver_channel_id,
        "post_close_claim.receiver_channel_id",
    )?;
    require_equal(
        &public_inputs.close_intent_digest,
        &descriptor.close_intent_digest,
        "post_close_claim.close_intent_digest",
    )?;
    require_equal(
        &public_inputs.incoming_tx_hash,
        &descriptor.incoming_tx_hash,
        "post_close_claim.incoming_tx_hash",
    )?;
    require_equal(
        &public_inputs.receiver_pk_g,
        &descriptor.receiver_pk_g,
        "post_close_claim.receiver_pk_g",
    )?;
    require_equal(
        &public_inputs.recipient,
        &descriptor.recipient,
        "post_close_claim.recipient",
    )?;
    require_equal(
        &public_inputs.shared_native_nullifier,
        &descriptor.shared_native_nullifier,
        "post_close_claim.shared_native_nullifier",
    )?;
    require_equal(
        &public_inputs.amount,
        &descriptor.amount,
        "post_close_claim.amount",
    )?;
    require_equal(
        &public_inputs.token_index,
        &descriptor.token_index,
        "post_close_claim.token_index",
    )
}

fn validate_cancel_close_binding() -> Result<(), String> {
    let descriptor: CancelCloseDescriptor =
        strict_value("cancel_close.json", &json_value("cancel_close.json")?)?;
    let public_inputs = CancelClosePublicInputs::from_u64_slice(&parse_full_public_inputs(
        "cancel_close_mle.json",
    )?)?;
    require_equal(
        &public_inputs.channel_id.channel_id(),
        &descriptor.channel_id,
        "cancel_close.channel_id",
    )?;
    require_equal(
        &public_inputs.close_intent_digest,
        &descriptor.close_intent_digest,
        "cancel_close.close_intent_digest",
    )?;
    require_equal(
        &public_inputs.member_set_commitment,
        &descriptor.member_set_commitment,
        "cancel_close.member_set_commitment",
    )?;
    require_equal(
        &public_inputs.close_final_state_version,
        &descriptor.close_final_state_version,
        "cancel_close.close_final_state_version",
    )?;
    require_equal(
        &public_inputs.revived_state_version,
        &descriptor.revived_state_version,
        "cancel_close.revived_state_version",
    )?;
    require_equal(
        &public_inputs.revived_channel_state_digest,
        &descriptor.revived_channel_state_digest,
        "cancel_close.revived_channel_state_digest",
    )?;
    require_equal(
        &descriptor.member_set_commitment,
        &padded_member_commitment(&descriptor.member_pk_gs)?,
        "cancel_close recomputed member_set_commitment",
    )
}

fn validate_partial_withdrawal_bindings() -> Result<(), String> {
    let registration: PartialWithdrawalRegistrationDescriptor =
        strict_value("pw_reg.json", &json_value("pw_reg.json")?)?;
    let submit: PartialWithdrawalSubmitDescriptor =
        strict_value("pw_submit.json", &json_value("pw_submit.json")?)?;
    let public_inputs = ChannelClosePublicInputs::from_u64_slice(&parse_full_public_inputs(
        "pw_close_intent_mle.json",
    )?)
    .map_err(|e| e.to_string())?;

    require_equal(
        &public_inputs.channel_id.channel_id(),
        &registration.channel_id,
        "partial withdrawal close channel_id",
    )?;
    require_equal(
        &public_inputs.member_count,
        &registration.member_count,
        "partial withdrawal close member_count",
    )?;
    require_equal(
        &public_inputs.delegate_count,
        &registration.active_delegate_count,
        "partial withdrawal close delegate_count",
    )?;
    require_equal(
        &public_inputs.member_set_commitment,
        &padded_member_commitment(&registration.member_pk_gs)?,
        "partial withdrawal registered member-set commitment",
    )?;
    if registration.reg_delegate_count != 0 {
        return Err("pw_reg reg_delegate_count must remain the cosigner-only zero".to_owned());
    }
    if submit.manager == submit.verifier {
        return Err("pw_submit manager and verifier addresses alias".to_owned());
    }
    if !registration
        .recipients
        .contains(&submit.withdrawal_recipient)
    {
        return Err(
            "pw_submit withdrawal recipient is not one of the registered payout recipients"
                .to_owned(),
        );
    }

    require_equal(
        &public_inputs.close_nonce,
        &submit.close_nonce,
        "pw_submit.close_nonce",
    )?;
    require_equal(
        &public_inputs.final_epoch,
        &submit.final_epoch,
        "pw_submit.final_epoch",
    )?;
    require_equal(
        &public_inputs.final_small_block_number,
        &submit.final_small_block_number,
        "pw_submit.final_small_block_number",
    )?;
    require_equal(
        &public_inputs.close_freeze_nonce,
        &submit.close_freeze_nonce,
        "pw_submit.close_freeze_nonce",
    )?;
    require_equal(
        &public_inputs.final_channel_state_digest,
        &submit.final_channel_state_digest,
        "pw_submit.final_channel_state_digest",
    )?;
    require_equal(
        &public_inputs.final_balance_state_h1,
        &submit.final_balance_state_h1,
        "pw_submit.final_balance_state_h1",
    )?;
    require_equal(
        &public_inputs.channel_fund_intmax_state_root,
        &submit.channel_fund_intmax_state_root,
        "pw_submit.channel_fund_intmax_state_root",
    )?;
    require_equal(
        &public_inputs.burn_tx_hash,
        &submit.burn_tx_hash,
        "pw_submit.burn_tx_hash",
    )?;
    require_equal(
        &public_inputs.close_withdrawal_digest,
        &submit.close_withdrawal_digest,
        "pw_submit.close_withdrawal_digest",
    )?;
    require_equal(
        &public_inputs.snapshot_medium_block_number,
        &submit.snapshot_medium_block_number,
        "pw_submit.snapshot_medium_block_number",
    )?;
    require_equal(
        &public_inputs.final_state_version,
        &submit.final_state_version,
        "pw_submit.final_state_version",
    )?;
    require_equal(
        &public_inputs.final_settled_tx_chain,
        &submit.final_settled_tx_chain,
        "pw_submit.final_settled_tx_chain",
    )?;
    require_equal(
        &public_inputs.final_settled_tx_accumulator_root,
        &submit.final_settled_tx_acc_root,
        "pw_submit.final_settled_tx_acc_root",
    )?;

    let (registry, amounts) = fixed_token_vectors(
        &submit.token_registry,
        &submit.channel_fund_amounts,
        "pw_submit",
    )?;
    if submit.token_count == 0 || usize::from(submit.token_count) > MAX_CHANNEL_TOKENS {
        return Err("pw_submit token_count is outside the fixed-width registry".to_owned());
    }
    require_equal(
        &public_inputs.channel_fund_amount,
        &amounts[0],
        "pw_submit native scalar/amounts[0]",
    )?;
    require_equal(
        &public_inputs.token_funds_digest,
        &token_funds_digest(&registry, submit.token_count, &amounts),
        "pw_submit token_funds_digest",
    )?;
    let withdrawal_slot = registry[..usize::from(submit.token_count)]
        .iter()
        .position(|token| *token == submit.withdrawal_token_index)
        .ok_or_else(|| {
            "pw_submit withdrawal token is absent from the active registry".to_owned()
        })?;
    if U256::from(submit.withdrawal_amount) > amounts[withdrawal_slot] {
        return Err("pw_submit withdrawal exceeds the proved per-token fund".to_owned());
    }
    require_equal(
        &settled_tx_chain_push(submit.prev_settled_tx_chain, submit.withdrawal_aux_data),
        &submit.final_settled_tx_chain,
        "pw_submit settled transaction chain push",
    )?;
    nonzero_word(
        submit.withdrawal_nullifier,
        "pw_submit.withdrawal_nullifier",
    )?;
    let _ = (
        submit.withdrawal_aux_data,
        submit.withdrawal_base_nonce,
        registration.member_pk_bs,
        registration.regev_pk_digests,
    );
    Ok(())
}

#[test]
fn all_companions_bind_to_their_proofs_and_release_relationships() {
    fn record<T>(errors: &mut Vec<String>, label: &str, result: Result<T, String>) -> Option<T> {
        match result {
            Ok(value) => Some(value),
            Err(error) => {
                errors.push(format!("{label}: {error}"));
                None
            }
        }
    }

    let mut errors = Vec::new();
    record(
        &mut errors,
        "standalone validity companions",
        validate_standalone_validity_companions(),
    );
    for (lifecycle, validity, payout, withdrawal, full_close) in [
        (
            "lifecycle.json",
            "lifecycle_validity_mle.json",
            "withdrawal_payout.json",
            "withdrawal_mle.json",
            false,
        ),
        (
            "close_lifecycle.json",
            "close_lifecycle_validity_mle.json",
            "close_withdrawal_payout.json",
            "close_withdrawal_mle.json",
            true,
        ),
        (
            "sepolia_lifecycle.json",
            "sepolia_lifecycle_validity_mle.json",
            "sepolia_withdrawal_payout.json",
            "sepolia_withdrawal_mle.json",
            false,
        ),
        (
            "burn_lifecycle.json",
            "burn_lifecycle_validity_mle.json",
            "burn_withdrawal_payout.json",
            "burn_withdrawal_mle.json",
            false,
        ),
    ] {
        record(
            &mut errors,
            lifecycle,
            validate_lifecycle_pair(lifecycle, validity, payout, withdrawal, full_close),
        );
    }
    record(&mut errors, "c2c lifecycle", validate_c2c_lifecycle_pair());

    let close = record(&mut errors, "close intent", validate_close_intent_binding());
    let close_lifecycle = record(
        &mut errors,
        "close lifecycle descriptor",
        strict_value::<LifecycleDescriptor>(
            "close_lifecycle.json",
            &json_value("close_lifecycle.json").expect("close lifecycle JSON"),
        ),
    );
    let close_payout = record(
        &mut errors,
        "close payout descriptor",
        strict_value::<PayoutDescriptor>(
            "close_withdrawal_payout.json",
            &json_value("close_withdrawal_payout.json").expect("close payout JSON"),
        ),
    );
    if let (Some(close), Some(close_lifecycle), Some(close_payout)) =
        (close, close_lifecycle, close_payout)
    {
        record(
            &mut errors,
            "close intent/backing statement",
            validate_close_backing_binding(&close, &close_lifecycle),
        );
        record(
            &mut errors,
            "close intent/lifecycle channel",
            require_equal(
                &close.channel_id,
                &close_lifecycle.registration.channel_id,
                "close intent/lifecycle channel_id",
            ),
        );
        record(
            &mut errors,
            "close intent/lifecycle member keys",
            require_equal(
                &close.member_pk_gs,
                &close_lifecycle.registration.member_pk_gs,
                "close intent/lifecycle registered member keys",
            ),
        );
        match (
            close.channel_fund_amounts.first(),
            close_payout.withdrawals.first(),
        ) {
            (Some(close_amount), Some(withdrawal)) => {
                record(
                    &mut errors,
                    "close intent/payout amount",
                    require_equal(
                        close_amount,
                        &withdrawal.amount,
                        "close intent native fund/payout amount",
                    ),
                );
            }
            _ => errors
                .push("close intent/payout amount: missing native amount or withdrawal".to_owned()),
        }
    }
    // The exact CREATE2 manager address depends on freshly deployed verifier initcode. Step 4's
    // required, non-skipping CloseLifecycleE2E suite recomputes that address and compares it to
    // this already schema-checked, nonzero payout recipient.

    record(
        &mut errors,
        "withdrawal claim",
        validate_withdrawal_claim_binding(),
    );
    record(
        &mut errors,
        "post-close claim",
        validate_post_close_claim_binding(),
    );
    record(&mut errors, "cancel close", validate_cancel_close_binding());
    record(
        &mut errors,
        "partial withdrawal",
        validate_partial_withdrawal_bindings(),
    );

    assert!(
        errors.is_empty(),
        "companion generation cohort is mixed:\n{}",
        errors.join("\n")
    );
}

#[test]
fn all_proof_free_configs_form_one_complete_current_generation_cohort() {
    let expected: BTreeSet<&str> = LIVE_CONFIG_COHORT.iter().copied().collect();
    let discovered: BTreeSet<String> = fs::read_dir(data_path("."))
        .expect("read contracts/test/data")
        .map(|entry| entry.expect("read fixture directory entry"))
        .filter(|entry| entry.file_type().expect("fixture file type").is_file())
        .filter_map(|entry| {
            let name = entry.file_name().to_string_lossy().into_owned();
            (name == "mle_fixture_config.json" || name.ends_with("_mle_config.json"))
                .then_some(name)
        })
        .collect();
    assert_eq!(
        discovered,
        expected.iter().map(|name| (*name).to_string()).collect(),
        "the proof-free config cohort changed; update the explicit release manifest and generate the entire cohort before deployment"
    );

    let expected_magic = std::str::from_utf8(&COMPACT_MAGIC_V2).expect("compact magic is ASCII");
    for name in LIVE_CONFIG_COHORT {
        let config = parse_config(name);
        assert_eq!(
            config.schema, MLE_VERIFIER_CONFIG_FIXTURE_SCHEMA_V2,
            "{name}: stale or mixed schema"
        );
        assert_eq!(
            config.schema_version, SCHEMA_VERSION_CURRENT,
            "{name}: schema generation"
        );
        assert_eq!(
            config.protocol_version, MLE_PROTOCOL_VERSION_CURRENT,
            "{name}: protocol generation"
        );
        assert_eq!(
            config.verification_key.protocol_version, MLE_PROTOCOL_VERSION_CURRENT,
            "{name}: VK protocol generation"
        );
        assert_eq!(config.whir_pow_bits, WHIR_POW_BITS_V2, "{name}: WHIR PoW");
        assert_eq!(
            config.compact_proof_encoding, expected_magic,
            "{name}: compact magic"
        );

        let wire_map = config
            .verification_key
            .public_input_wire_map
            .strip_prefix("0x")
            .unwrap_or_else(|| panic!("{name}: public-input wire map lacks 0x prefix"));
        assert_eq!(
            wire_map.len(),
            6 * config.verification_config.circuit.num_public_inputs,
            "{name}: public-input wire map must contain exactly one packed (u16 row,u8 column) entry per PI"
        );
    }

    let validity = parse_config("mle_fixture_config.json");
    for alias in [
        "lifecycle_validity_mle_config.json",
        "close_lifecycle_validity_mle_config.json",
        "c2c_lifecycle_validity_mle_config.json",
        "burn_lifecycle_validity_mle_config.json",
        "sepolia_lifecycle_validity_mle_config.json",
    ] {
        assert_eq!(
            parse_config(alias),
            validity,
            "{alias}: validity config drift"
        );
    }
    let withdrawal = parse_config("withdrawal_mle_config.json");
    for alias in [
        "close_withdrawal_mle_config.json",
        "c2c_withdrawal_mle_config.json",
        "burn_withdrawal_mle_config.json",
        "sepolia_withdrawal_mle_config.json",
    ] {
        assert_eq!(
            parse_config(alias),
            withdrawal,
            "{alias}: withdrawal config drift"
        );
    }

    let production = [
        ("validity", validity),
        ("withdrawal", withdrawal),
        ("close", parse_config("close_intent_mle_config.json")),
        (
            "withdrawal claim",
            parse_config("withdrawal_claim_mle_config.json"),
        ),
        (
            "post-close claim",
            parse_config("post_close_claim_mle_config.json"),
        ),
        ("cancel close", parse_config("cancel_close_mle_config.json")),
        (
            "close asset backing",
            parse_config("close_asset_backing_mle_config.json"),
        ),
    ];
    for left in 0..production.len() {
        for right in (left + 1)..production.len() {
            assert_ne!(
                production[left].1, production[right].1,
                "{} and {} unexpectedly share one verifier config",
                production[left].0, production[right].0
            );
        }
    }
}

#[test]
fn tracked_live_full_v2_fixtures_are_exhaustive_and_match_configs() {
    let expected_full: BTreeSet<&str> = LIVE_FULL_CONFIG_PAIRS
        .iter()
        .map(|(full, _)| *full)
        .collect();
    let expected_configs: BTreeSet<&str> = LIVE_FULL_CONFIG_PAIRS
        .iter()
        .map(|(_, config)| *config)
        .collect();

    let mut discovered_full = BTreeSet::new();
    let mut discovered_configs = BTreeSet::new();
    for entry in fs::read_dir(data_path(".")).expect("read contracts/test/data") {
        let entry = entry.expect("read fixture directory entry");
        if !entry.file_type().expect("fixture file type").is_file() {
            continue;
        }
        let name = entry.file_name();
        let name = name.to_string_lossy();
        let conventionally_full = name == "mle_fixture.json" || name.ends_with("_mle.json");
        let conventionally_config = name.ends_with("_mle_config.json");
        let schema = if name.ends_with(".json") {
            let path = entry.path();
            let value: serde_json::Value = serde_json::from_str(
                &fs::read_to_string(&path)
                    .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display())),
            )
            .unwrap_or_else(|e| panic!("{} is not valid JSON: {e}", path.display()));
            value
                .get("schema")
                .and_then(serde_json::Value::as_str)
                .map(str::to_owned)
        } else {
            None
        };
        if conventionally_full || schema.as_deref() == Some("plonky2-mle-v3-solidity") {
            discovered_full.insert(name.into_owned());
        } else if conventionally_config
            || schema.as_deref() == Some("plonky2-mle-v3-solidity-config")
        {
            discovered_configs.insert(name.into_owned());
        }
    }

    assert_eq!(
        discovered_full,
        expected_full.iter().map(|s| (*s).to_string()).collect(),
        "the live full-proof fixture set changed; update the explicit release manifest rather than silently skipping it"
    );
    assert_eq!(
        discovered_configs,
        expected_configs.iter().map(|s| (*s).to_string()).collect(),
        "the proof-free config fixture set changed; every live config must be explicitly paired with its full proofs"
    );

    for (full_name, config_name) in LIVE_FULL_CONFIG_PAIRS {
        let full = read(full_name);
        let config = read(config_name);
        let parsed_full = MleVerifierV2Fixture::from_canonical_json(&full).unwrap_or_else(|e| {
            panic!("{full_name} is not a strict canonical full V2 fixture: {e}")
        });
        assert_eq!(
            parsed_full.schema, MLE_VERIFIER_FIXTURE_SCHEMA_V2,
            "{full_name}: stale or mixed full-fixture schema"
        );
        let compact = validate_mle_v2_full_against_config_json(&full, &config)
            .unwrap_or_else(|e| panic!("{full_name} does not strictly match {config_name}: {e}"));
        assert!(!compact.is_empty(), "{full_name}: compact proof is empty");

        // Explicitly pin schema separation: neither parser may accept the other artifact class.
        assert!(
            MleVerifierV2Fixture::from_canonical_json(&config).is_err(),
            "{config_name}: config-only artifact was accepted as a full proof"
        );
        assert!(
            MleVerifierV2ConfigFixture::from_canonical_json(&full).is_err(),
            "{full_name}: full proof was accepted as a config-only artifact"
        );
    }

    // Prefix variants are witnesses for the same two circuits, not independent statement
    // configurations. Pin their identity so a variant cannot quietly deploy a different verifier.
    let validity = parse_config("mle_fixture_config.json");
    for alias in [
        "lifecycle_validity_mle_config.json",
        "close_lifecycle_validity_mle_config.json",
        "c2c_lifecycle_validity_mle_config.json",
        "burn_lifecycle_validity_mle_config.json",
        "sepolia_lifecycle_validity_mle_config.json",
    ] {
        assert_eq!(
            parse_config(alias),
            validity,
            "{alias}: validity config drift"
        );
    }
    let withdrawal = parse_config("withdrawal_mle_config.json");
    for alias in [
        "close_withdrawal_mle_config.json",
        "c2c_withdrawal_mle_config.json",
        "burn_withdrawal_mle_config.json",
        "sepolia_withdrawal_mle_config.json",
    ] {
        assert_eq!(
            parse_config(alias),
            withdrawal,
            "{alias}: withdrawal config drift"
        );
    }

    // The seven production statements must remain distinct constructor identities. Accidental
    // cross-family config reuse would otherwise let a full proof appear internally consistent
    // while deployment wires the wrong statement verifier.
    let production = [
        ("validity", validity),
        ("withdrawal", withdrawal),
        ("close", parse_config("close_intent_mle_config.json")),
        (
            "withdrawal claim",
            parse_config("withdrawal_claim_mle_config.json"),
        ),
        (
            "post-close claim",
            parse_config("post_close_claim_mle_config.json"),
        ),
        ("cancel close", parse_config("cancel_close_mle_config.json")),
        (
            "close asset backing",
            parse_config("close_asset_backing_mle_config.json"),
        ),
    ];
    for left in 0..production.len() {
        for right in (left + 1)..production.len() {
            assert_ne!(
                production[left].1, production[right].1,
                "{} and {} unexpectedly share one V2 config",
                production[left].0, production[right].0
            );
        }
    }
}

#[test]
fn validity_downstream_artifacts_commit_to_exact_compact_v2_bytes() {
    let expected_companions: BTreeSet<&str> = VALIDITY_DA_COMPANIONS
        .iter()
        .map(|(_, _, companion)| *companion)
        .collect();
    let mut discovered_companions = BTreeSet::new();
    for entry in fs::read_dir(data_path(".")).expect("read contracts/test/data") {
        let entry = entry.expect("read fixture directory entry");
        let name = entry.file_name().to_string_lossy().into_owned();
        if !entry.file_type().expect("fixture file type").is_file() || !name.ends_with(".json") {
            continue;
        }
        let value: serde_json::Value = serde_json::from_str(&read(&name))
            .unwrap_or_else(|e| panic!("{name}: invalid JSON: {e}"));
        let has_hash = value.get("proof_hash").is_some();
        let has_length = value.get("proof_length").is_some();
        assert_eq!(
            has_hash, has_length,
            "{name}: proof_hash and proof_length must appear together"
        );
        if has_hash {
            discovered_companions.insert(name);
        }
    }
    assert_eq!(
        discovered_companions,
        expected_companions
            .iter()
            .map(|name| (*name).to_string())
            .collect(),
        "the Proof-DA companion set changed; bind every descriptor explicitly to its full V2 proof"
    );

    for (full_name, config_name, companion_name) in VALIDITY_DA_COMPANIONS {
        let (expected_hash, expected_length) =
            mle_v2_compact_submission_metadata(&read(full_name), &read(config_name))
                .unwrap_or_else(|e| panic!("{full_name}/{config_name}: {e}"));
        let companion: serde_json::Value = serde_json::from_str(&read(companion_name))
            .unwrap_or_else(|e| panic!("{companion_name}: invalid JSON: {e}"));
        let actual_hash = companion["proof_hash"]
            .as_str()
            .unwrap_or_else(|| panic!("{companion_name}: missing string proof_hash"));
        let actual_length = companion["proof_length"]
            .as_u64()
            .unwrap_or_else(|| panic!("{companion_name}: missing integer proof_length"));
        assert_eq!(
            actual_hash.to_ascii_lowercase(),
            expected_hash,
            "{companion_name}: proof_hash must be keccak256({full_name}.compactProof.bytes)"
        );
        assert_eq!(
            actual_length,
            u64::from(expected_length),
            "{companion_name}: proof_length must be the exact compactProof byte length"
        );
    }
}

#[test]
fn production_statement_profiles_are_explicitly_pinned_for_resource_admission() {
    let mut max_public_inputs = 0;
    let mut max_gate_rows = 0;
    for &(name, public_inputs, constants, selectors, max_compact_bytes, config_abi_hash) in
        PRODUCTION_RESOURCE_PROFILES
    {
        let config = parse_config(name);
        let circuit = &config.verification_config.circuit;
        assert_eq!(circuit.degree_bits, 13, "{name}: row dimension drift");
        assert_eq!(
            circuit.num_public_inputs, public_inputs,
            "{name}: PI count drift"
        );
        assert_eq!(
            circuit.num_constants, constants,
            "{name}: constant count drift"
        );
        assert_eq!(circuit.num_routed_wires, 80, "{name}: routed-wire drift");
        assert_eq!(circuit.num_wires, 135, "{name}: wire count drift");
        assert_eq!(
            circuit.num_selectors, selectors,
            "{name}: selector count drift"
        );
        assert_eq!(
            circuit.num_gate_constraints, 123,
            "{name}: constraint count drift"
        );
        assert_eq!(
            circuit.quotient_degree_factor, 8,
            "{name}: quotient degree drift"
        );
        assert_eq!(
            config.verification_config.gates.len(),
            13,
            "{name}: gate-row drift"
        );
        assert_eq!(
            config.solidity_abi_verification_config.keccak256, config_abi_hash,
            "{name}: complete constructor configuration drift requires fresh gas/size admission"
        );
        assert_eq!(
            config.compact_shape.constituent_width, 160,
            "{name}: packed width drift"
        );
        assert_eq!(
            config.size_upper_bound.max_compact_bytes, max_compact_bytes,
            "{name}: compact grammar bound drift"
        );
        assert!(
            config.size_upper_bound.fits_whir_blob_caps,
            "{name}: WHIR blob overflow"
        );
        assert!(
            config.size_upper_bound.fits_compact_cap,
            "{name}: compact DA overflow"
        );
        max_public_inputs = max_public_inputs.max(circuit.num_public_inputs);
        max_gate_rows = max_gate_rows.max(config.verification_config.gates.len());
    }
    assert_eq!(max_public_inputs, 103, "parent production PI maximum drift");
    assert_eq!(
        max_gate_rows, 13,
        "parent production gate-row maximum drift"
    );
}

#[test]
fn max_resource_fixture_has_one_strict_canonical_compact_proof() {
    let path = repo_root()
        .join("contracts/lib/polygon-plonky2/mle/contracts/test/fixtures/v2_max_resource.json");
    let full =
        fs::read_to_string(&path).unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    let parsed = MleVerifierV2Fixture::from_canonical_json(&full)
        .unwrap_or_else(|e| panic!("{} is not strict canonical v2: {e}", path.display()));
    let config = parsed
        .config_fixture()
        .to_canonical_json()
        .expect("project max-resource config");
    let compact = validate_mle_v2_full_against_config_json(&full, &config)
        .unwrap_or_else(|e| panic!("{} failed compact/config integrity: {e}", path.display()));
    assert!(!compact.is_empty());
}
