// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {BlobKZGVerifierExt} from "../src/BlobKZGVerifier.sol";
import {MleVerifier} from "@mle/MleVerifier.sol";
import {FixtureLib} from "../script/FixtureLib.sol";

contract BlobKZGVerifierHarness is BlobKZGVerifierExt {
    function blobWord(bytes calldata proofBytes, uint256 blobIndex, uint256 wordIndex)
        external
        pure
        returns (bytes32 word)
    {
        bytes memory blob = new bytes(BYTES_PER_BLOB);
        uint256 ptr;
        assembly ("memory-safe") { ptr := add(blob, 32) }
        _fillSimpleCoderBlob(proofBytes, blobIndex, ptr);
        assembly ("memory-safe") { word := mload(add(ptr, mul(wordIndex, 32))) }
    }

    function evaluation(bytes calldata proofBytes, uint256 blobIndex, bytes calldata commitment)
        external
        view
        returns (bytes32 versionedHash, uint256 z, uint256 y)
    {
        return _blobEvaluation(proofBytes, blobIndex, commitment);
    }

    function count(uint256 proofLength) external pure returns (uint8) {
        return _blobCount(proofLength);
    }

    function commitment(
        bytes32 blobHash0,
        bytes32 blobHash1,
        uint8 blobCount,
        bytes32 stateRoot,
        uint64 submittedAtBlock,
        uint256 submissionId
    ) external pure returns (bytes32) {
        return _commitment(
            blobHash0,
            blobHash1,
            blobCount,
            stateRoot,
            submittedAtBlock,
            submissionId
        );
    }
}

/// @notice Proof-DA v2 regression tests. The first vector was generated by Foundry 1.5.1's
///         `cast mktx --blob --path` and therefore joins the exact Alloy SimpleCoder blob to the
///         standard Ethereum-ceremony commitment/proof consumed by precompile 0x0a.
contract BlobKzgPairingTest is Test {
    BlobKZGVerifierHarness internal verifier;

    uint256 internal constant BLS_MODULUS =
        0x73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001;
    bytes32 internal constant PROOF_DA_DOMAIN = keccak256("INTMAX3_PROOF_DA_V3");

    function setUp() public {
        verifier = new BlobKZGVerifierHarness();
    }

    function test_castSimpleCoderGolden_standardPointEvaluationProof() public view {
        // The source file contained the four bytes "abc\n". Cast produced FE0/FE1 exactly as
        // asserted below, then the standard c-kzg commitment and blob proof embedded here.
        bytes memory payload = hex"6162630a";
        assertEq(
            verifier.blobWord(payload, 0, 0),
            0x0000000000000000040000000000000000000000000000000000000000000000,
            "FE0 must be 0x00 || u64_be(length) || 23 zero bytes"
        );
        assertEq(
            verifier.blobWord(payload, 0, 1),
            0x006162630a000000000000000000000000000000000000000000000000000000,
            "FE1 must be 0x00 || payload[0:31]"
        );

        bytes memory commitment =
            hex"99286fb3dd61b63bade1c18561ea7c312f52efa4a8dd8b5b2bf4cd238bae270d0503e3d3aca779414c00312c8fd85596";
        bytes memory proof =
            hex"993e421e329cae93d0bc282910dc6999fe1a66a763c21ac31df45faf792746c042fd8e7f3095531188c77dc457f987ae";

        (bytes32 evaluatedHash, uint256 z, uint256 y) = verifier.evaluation(payload, 0, commitment);
        assertEq(evaluatedHash, 0x01a8ca638239641d743640160da7cfa710d92709bbdd27c340b92d57b6f9e19a);
        assertEq(z, 0x6502fe7bc276889ec93bfe7a0f598ef512a8b0613e328a9889b12d5fe93853c6);
        assertEq(y, 0x7116fe3ddee33c4664b3cbb07d74470b3644180971194792b21548d8e8b09fd7);

        (bytes32 blobHash, bytes32 second, uint8 count) = verifier.verify(
            payload, bytes.concat(commitment, proof)
        );
        assertEq(blobHash, 0x01a8ca638239641d743640160da7cfa710d92709bbdd27c340b92d57b6f9e19a);
        assertEq(second, bytes32(0));
        assertEq(count, 1);
    }

    function test_castProductionArtifactTwoBlob_standardPointEvaluationProofs() public view {
        // Reproducible generation:
        //   forge script script/PrepareProofDa.s.sol:PrepareProofDa --offline
        //   cast mktx --blob --path ../proof-da-output/validity-proof.bin <signed tx args>
        //   | cast decode-transaction --json
        // The payload is regenerated from the tracked source fixture here, not checked in as a
        // 130 KiB opaque binary. Both c-kzg blob proofs execute against the real 0x0a precompile.
        string memory json = vm.readFile(
            string.concat(vm.projectRoot(), "/test/data/sepolia_lifecycle_validity_mle.json")
        );
        MleVerifier.MleProof memory mleProof = FixtureLib.parseProof(json);
        bytes memory payload = abi.encode(mleProof);
        assertEq(payload.length, 130_592);
        assertEq(
            keccak256(payload),
            0x93b18c568e154d895a698da7712cea7f88e195e110501cca65e2f28c1a3d691b
        );

        bytes memory commitment0 =
            hex"8eb25df2c6262ffa4885ae2bb491a2488c718d6b50ce6bf9be315a3e0bcf6092e33a7120a658f10dc8ec771dca6a6ac2";
        bytes memory proof0 =
            hex"b9543e26c5c9d7f94bcf664472e65f242afae1d853269259a51e9d60be873ac2b7e9db72d4520d55769e49cd62131b29";
        bytes memory commitment1 =
            hex"abaa69d3c82e25709971900eaa27c2d63bbd159a05f089a8cb299d64436101cafc8470e9e0c56d785a28174bf5e54bbb";
        bytes memory proof1 =
            hex"affa4a1516425bbcb59bb07f58499f29cd519bc7decdffbd4cf22fa59280763ebcab82d7d246fb33de2fe34174954c3a";

        (bytes32 blobHash0, bytes32 blobHash1, uint8 count) = verifier.verify(
            payload, bytes.concat(commitment0, proof0, commitment1, proof1)
        );
        assertEq(blobHash0, 0x013aece36c6d6fd1c086a3be3fa73da5bc44b4e8e9b0eef108c58e980ced6681);
        assertEq(blobHash1, 0x0145cdb30fad5803d3895ef8ef47569b296448f1b6864f3311f02ab3163fbc74);
        assertEq(count, 2);
    }

    function test_independentChallengeAndBarycentricVector() public view {
        bytes memory payload =
            hex"80ff000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20";
        bytes memory commitment = new bytes(48);
        for (uint256 i = 0; i < 48; i++) commitment[i] = 0x11;

        assertEq(
            verifier.blobWord(payload, 0, 0),
            0x0000000000000000230000000000000000000000000000000000000000000000
        );
        assertEq(
            verifier.blobWord(payload, 0, 1),
            0x0080ff000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c
        );
        assertEq(
            verifier.blobWord(payload, 0, 2),
            0x001d1e1f20000000000000000000000000000000000000000000000000000000
        );

        (bytes32 blobHash, uint256 z, uint256 y) = verifier.evaluation(payload, 0, commitment);
        assertEq(blobHash, 0x01a127dff9f9bbfa1dff5275a99464123998e95bf11dd579f2ffcab301bc7350);
        assertEq(z, 0x65fa4ca37ebeadade08c959a8d1f0cf28a5061156ea9228f857bab035cc8e9ce);
        assertEq(y, 0x30343f60c266a5b9e985184f9c4f6a4d9619fa646ea1734159dea36316556adb);
    }

    function test_exactOneOrTwoBlobBoundaries() public {
        assertEq(verifier.count(126_945), 1);
        assertEq(verifier.count(126_946), 2);
        assertEq(verifier.count(253_921), 2);

        vm.expectRevert(BlobKZGVerifierExt.EmptyProofPayload.selector);
        verifier.count(0);
        vm.expectRevert(
            abi.encodeWithSelector(BlobKZGVerifierExt.ProofPayloadTooLarge.selector, 253_922)
        );
        verifier.count(253_922);
    }

    function test_twoBlobSplitContinuesPayloadWithoutSecondHeader() public view {
        bytes memory payload = new bytes(126_946);
        payload[126_944] = 0xaa;
        payload[126_945] = 0xbb;

        assertEq(
            verifier.blobWord(payload, 0, 4095),
            0x00000000000000000000000000000000000000000000000000000000000000aa
        );
        assertEq(
            verifier.blobWord(payload, 1, 0),
            0x00bb000000000000000000000000000000000000000000000000000000000000
        );
    }

    function test_highBitPayloadIsLosslessAndCannotMaskCollide() public view {
        bytes memory high = new bytes(31);
        bytes memory low = new bytes(31);
        high[0] = 0x80;

        bytes32 highWord = verifier.blobWord(high, 0, 1);
        bytes32 lowWord = verifier.blobWord(low, 0, 1);
        assertEq(highWord, 0x0080000000000000000000000000000000000000000000000000000000000000);
        assertTrue(highWord != lowWord, "SimpleCoder must not mask high payload bits");
        assertTrue(uint256(highWord) < BLS_MODULUS, "31-byte payload is a canonical Fr element");
    }

    function test_blobMetadataRejectsMissingAndExtraBlobs() public {
        bytes32[] memory none = new bytes32[](0);
        vm.blobhashes(none);
        vm.expectRevert(abi.encodeWithSelector(BlobKZGVerifierExt.MissingBlob.selector, 0));
        verifier.blobMetadata(1);

        bytes32[] memory two = new bytes32[](2);
        two[0] = bytes32(uint256(1));
        two[1] = bytes32(uint256(2));
        vm.blobhashes(two);
        vm.expectRevert(abi.encodeWithSelector(BlobKZGVerifierExt.ExtraBlob.selector, 1));
        verifier.blobMetadata(1);

        bytes32[] memory one = new bytes32[](1);
        one[0] = bytes32(uint256(1));
        vm.blobhashes(one);
        vm.expectRevert(abi.encodeWithSelector(BlobKZGVerifierExt.MissingBlob.selector, 1));
        verifier.blobMetadata(126_946);
    }

    function test_compactSidecarRejectsMissingAndExtraEvidence() public {
        bytes memory payload = hex"01";
        vm.expectRevert(
            abi.encodeWithSelector(BlobKZGVerifierExt.SidecarLengthMismatch.selector, 96, 0)
        );
        verifier.verify(payload, "");

        vm.expectRevert(
            abi.encodeWithSelector(BlobKZGVerifierExt.SidecarLengthMismatch.selector, 96, 192)
        );
        verifier.verify(payload, new bytes(192));
    }

    function test_twoBlobSidecarsAreOrderBound() public {
        bytes memory payload = new bytes(126_946);
        payload[0] = 0x41;
        payload[126_945] = 0x42;

        bytes memory commitment0 = new bytes(48);
        bytes memory proof0 = new bytes(48);
        bytes memory commitment1 = new bytes(48);
        bytes memory proof1 = new bytes(48);
        for (uint256 i = 0; i < 48; i++) {
            commitment0[i] = 0x11;
            proof0[i] = 0x22;
            commitment1[i] = 0x33;
            proof1[i] = 0x44;
        }

        (bytes32 h0, uint256 z0, uint256 y0) = verifier.evaluation(payload, 0, commitment0);
        (bytes32 h1, uint256 z1, uint256 y1) = verifier.evaluation(payload, 1, commitment1);
        bytes memory success = abi.encode(uint256(4096), BLS_MODULUS);
        vm.mockCall(
            address(0x0a),
            bytes.concat(h0, bytes32(z0), bytes32(y0), commitment0, proof0),
            success
        );
        vm.mockCall(
            address(0x0a),
            bytes.concat(h1, bytes32(z1), bytes32(y1), commitment1, proof1),
            success
        );

        (bytes32 opened0, bytes32 opened1, uint8 count) = verifier.verify(
            payload, bytes.concat(commitment0, proof0, commitment1, proof1)
        );
        assertEq(opened0, h0);
        assertEq(opened1, h1);
        assertEq(count, 2);

        vm.expectRevert(abi.encodeWithSelector(BlobKZGVerifierExt.PointEvaluationFailed.selector, 0));
        verifier.verify(payload, bytes.concat(commitment1, proof1, commitment0, proof0));
    }

    function test_standardProofRejectsOneBitPayloadCommitmentAndProofMutations() public {
        bytes memory payload = hex"6162630a";
        bytes memory commitment =
            hex"99286fb3dd61b63bade1c18561ea7c312f52efa4a8dd8b5b2bf4cd238bae270d0503e3d3aca779414c00312c8fd85596";
        bytes memory proof =
            hex"993e421e329cae93d0bc282910dc6999fe1a66a763c21ac31df45faf792746c042fd8e7f3095531188c77dc457f987ae";

        payload[0] ^= 0x01;
        vm.expectRevert(abi.encodeWithSelector(BlobKZGVerifierExt.PointEvaluationFailed.selector, 0));
        verifier.verify(payload, bytes.concat(commitment, proof));
        payload[0] ^= 0x01;

        commitment[0] ^= 0x01;
        vm.expectRevert(abi.encodeWithSelector(BlobKZGVerifierExt.PointEvaluationFailed.selector, 0));
        verifier.verify(payload, bytes.concat(commitment, proof));
        commitment[0] ^= 0x01;

        proof[0] ^= 0x01;
        vm.expectRevert(abi.encodeWithSelector(BlobKZGVerifierExt.PointEvaluationFailed.selector, 0));
        verifier.verify(payload, bytes.concat(commitment, proof));
    }

    function test_commitmentIsDomainSeparatedAndBindsEveryField() public view {
        bytes32 h0 = keccak256("blob 0");
        bytes32 h1 = keccak256("blob 1");
        bytes32 root = keccak256("root");
        bytes32 expected = keccak256(
            abi.encode(PROOF_DA_DOMAIN, h0, h1, uint8(2), root, uint64(9), uint256(7))
        );
        assertEq(verifier.commitment(h0, h1, 2, root, 9, 7), expected);
        assertTrue(verifier.commitment(h1, h0, 2, root, 9, 7) != expected);
        assertTrue(verifier.commitment(h0, h1, 1, root, 9, 7) != expected);
        assertTrue(verifier.commitment(h0, h1, 2, root, 10, 7) != expected);
        assertTrue(verifier.commitment(h0, h1, 2, root, 9, 8) != expected);
    }

    function test_pointEvaluationNoCodeOrShortReturnFailsClosed() public {
        bytes memory payload = hex"01";
        bytes memory sidecar = new bytes(96);

        // An empty-success response (the behavior of a no-code address) cannot pass: the
        // satellite requires exactly the 64-byte EIP-4844 precompile result.
        vm.mockCall(address(0x0a), bytes(""), bytes(""));
        vm.expectRevert(abi.encodeWithSelector(BlobKZGVerifierExt.PointEvaluationFailed.selector, 0));
        verifier.verify(payload, sidecar);
    }
}
