// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import {Verifier as GnarkVerifier} from "../src/GnarkGroth16Verifier.sol";
import {Verifier as WhirVerifier} from "sol-whir/Whir.sol";
import {WhirProof, Statement, WhirConfig} from "sol-whir/WhirStructs.sol";
import {BN254} from "solidity-bn254/BN254.sol";
import {JSONWhirProof, JSONUtils} from "sol-whir/utils/WhirJson.sol";

/// @title E2E test with REAL Groth16 (gnark) + REAL WHIR proof
/// @notice Verifies that:
///   1. A real gnark Groth16 proof (from Plonky2 validity circuit) passes on-chain verification
///   2. A real WHIR proof (BN254) passes sol-whir verification
///   3. Both are bound to the same piHash (keccak256 of ValidityPublicInputs)
contract E2E_RealGroth16Test is Test {

    function test_realGroth16_verifies() public {
        GnarkVerifier gnarkVerifier = new GnarkVerifier();

        // Load the E2E fixture
        string memory groth16Json = vm.readFile(
            string.concat(vm.projectRoot(), "/test/data/e2e_groth16.json")
        );

        // Parse raw proof hex: A(64) + B(128) + C(64) + nbCommit(4) + commit(64) + commitPok(64)
        bytes memory rawProof = abi.decode(vm.parseJson(groth16Json, ".raw_proof_hex"), (bytes));
        require(rawProof.length >= 388, "Raw proof too short");

        // Extract A+B+C (proof[8])
        uint256[8] memory proof;
        assembly {
            let src := add(rawProof, 32)
            for { let i := 0 } lt(i, 8) { i := add(i, 1) } {
                mstore(add(proof, mul(i, 32)), mload(add(src, mul(i, 32))))
            }
        }

        // Extract commitment (64 bytes at offset 260 = 256 + 4 for nbCommitments header)
        uint256[2] memory commitments;
        assembly {
            let src := add(add(rawProof, 32), 260) // skip length prefix + 260 bytes
            mstore(commitments, mload(src))
            mstore(add(commitments, 32), mload(add(src, 32)))
        }

        // Extract commitmentPok (64 bytes at offset 324)
        uint256[2] memory commitmentPok;
        assembly {
            let src := add(add(rawProof, 32), 324)
            mstore(commitmentPok, mload(src))
            mstore(add(commitmentPok, 32), mload(add(src, 32)))
        }

        // Parse 8 user public inputs (commitment hash computed internally by gnark v0.10 verifier)
        uint256[8] memory input;
        for (uint256 i = 0; i < 8; i++) {
            string memory key = string.concat(".public_inputs_hex[", vm.toString(i), "]");
            input[i] = abi.decode(vm.parseJson(groth16Json, key), (uint256));
        }

        // Verify — reverts with ProofInvalid() if verification fails
        gnarkVerifier.verifyProof(proof, commitments, commitmentPok, input);

        // If we reach here, the real Groth16 proof verified on-chain
        assertTrue(true, "Real gnark Groth16 proof verified on-chain");
    }

    function test_realWhir_verifies() public {
        // Load WHIR fixture bound to the same piHash
        string memory whirJson = vm.readFile(
            string.concat(vm.projectRoot(), "/test/data/whir/intmax3_e2e_whir_fixture.json")
        );
        bytes memory parsed = vm.parseJson(whirJson);
        JSONWhirProof memory jsonProof = abi.decode(parsed, (JSONWhirProof));

        WhirConfig memory config = JSONUtils.jsonWhirConfigToWhirConfig(jsonProof.config);
        Statement memory statement = JSONUtils.jsonStatementToStatement(jsonProof.statement);
        WhirProof memory whirProof = JSONUtils.jsonWhirProofToWhirProof(jsonProof);
        bytes memory transcript = jsonProof.arthur.transcript;

        bool ok = WhirVerifier.verify(config, statement, whirProof, transcript);
        assertTrue(ok, "Real WHIR proof verified on-chain");
    }

    function test_e2e_piHash_binding() public {
        // Load piHash from the E2E fixture (generated by Rust)
        string memory e2eJson = vm.readFile(
            string.concat(vm.projectRoot(), "/test/data/e2e_fixture.json")
        );
        bytes32 piHashReducedBytes = abi.decode(vm.parseJson(e2eJson, ".pi_hash_reduced"), (bytes32));
        uint256 piHashReduced = uint256(piHashReducedBytes);

        // Load WHIR fixture
        string memory whirJson = vm.readFile(
            string.concat(vm.projectRoot(), "/test/data/whir/intmax3_e2e_whir_fixture.json")
        );
        bytes memory parsed = vm.parseJson(whirJson);
        JSONWhirProof memory jsonProof = abi.decode(parsed, (JSONWhirProof));
        Statement memory statement = JSONUtils.jsonStatementToStatement(jsonProof.statement);

        // Verify binding: WHIR evaluations[0] == piHashReduced
        uint256 whirEval = BN254.ScalarField.unwrap(statement.evaluations[0]);
        assertEq(whirEval, piHashReduced, "WHIR evaluations[0] must equal piHashReduced");

        // Verify binding: Groth16 pubInputs encode the same piHash as 8 u32 limbs
        string memory groth16Json = vm.readFile(
            string.concat(vm.projectRoot(), "/test/data/e2e_groth16.json")
        );
        bytes32 piHash = abi.decode(vm.parseJson(e2eJson, ".pi_hash"), (bytes32));
        // Parse each public input individually (avoid Foundry JSON array sorting)
        bytes32 reconstructed;
        for (uint256 i = 0; i < 8; i++) {
            string memory key = string.concat(".public_inputs_hex[", vm.toString(i), "]");
            uint256 limb = abi.decode(vm.parseJson(groth16Json, key), (uint256));
            reconstructed = bytes32(uint256(reconstructed) | (limb << (224 - i * 32)));
        }
        assertEq(reconstructed, piHash, "Groth16 pubInputs must encode piHash");
    }
}
