import Std

/-!
# Keccak-256 reference specification

This module is a REFERENCE SPECIFICATION of an external algorithm, not a model of
an in-repo source file. It has NO in-repo source line: nothing in `src/` is
transcribed here, and no line of this file corresponds to a line of Rust or
Solidity.

What it specifies: Keccak-256 exactly as the EVM `KECCAK256` opcode computes it —
Keccak-f[1600] (theta, rho, pi, chi, iota; 24 rounds; the standard rotation-offset
table and the standard 24 round constants), sponge construction with rate 1088 bits
(136 bytes), the ORIGINAL Keccak padding `0x01 .. 0x80` (NOT the SHA-3 `0x06 .. 0x80`
domain separation), little-endian 8-byte lanes, 32-byte output taken from the first
four lanes of the final state.

Where the two sides of the system get Keccak-256 from, and why neither is translated
here:

* Circuit side: the in-circuit gadget is the external crate `plonky2_keccak`, pinned
  in `Cargo.lock` as
  `git+https://github.com/InternetMaximalism/plonky2_keccak?branch=wasm-main#2507786148ae6323d0ea547bf88e1752f901434e`.
  That crate is a third-party dependency and is OUTSIDE this audit's translation
  scope. Nothing in this module proves that the gadget computes `keccak256` below;
  that is a named trust-boundary premise elsewhere.
* Contract side: the Solidity code uses the EVM `KECCAK256` opcode, whose semantics
  are given by the EVM specification, not by any file in this repository. Again a
  named premise, not a theorem here.

So this module supplies a single concrete function that both premises can point at,
replacing two independent opaque callbacks by one pinned algorithm. NO collision
resistance, preimage resistance or injectivity is claimed or proved anywhere below;
those remain explicit assumptions in the trust-boundary module.

## Test vectors

The two published vectors (`keccak256 ""` and `keccak256 "abc"`) and two
self-generated vectors (a 135-byte message, which is the single-`0x81` padding
boundary, and a 200-byte message, which is two sponge blocks) were produced by an
independently written pure-Python Keccak-256 and cross-checked against the published
values before being transcribed here.

Every one of the four vectors is a KERNEL-PROVED theorem, discharged by `decide`:
`keccak256_empty_vector`, `keccak256_abc_vector`, `keccak256_pad_boundary_vector`,
`keccak256_two_block_vector`. No vector relies on compiled evaluation.

## Recursion discipline

All recursion is structural (recursion over a constant list of round constants, or
over an explicit fuel argument), so that the definitions reduce in the kernel and
`decide` is possible at all.
-/

namespace Zkp.Implementation.Keccak256

/-! ## Lane arithmetic

Lanes are `Nat` constrained to `< 2 ^ 64`; the 64-bit wrap is explicit `% 2 ^ 64`.
Bitwise operations are `Nat.land`, `Nat.lor`, `Nat.xor`, `Nat.shiftLeft`,
`Nat.shiftRight`, written with the standard notations. -/

/-- Lane width in bits. -/
def laneBits : Nat := 64

/-- `2 ^ 64`, the lane modulus. -/
def laneMod : Nat := 2 ^ 64

theorem lane_bits_pinned : laneBits = 64 := rfl

theorem lane_mod_pinned : laneMod = 18446744073709551616 := by decide

/-- All-ones 64-bit lane; `laneNot` below uses it as bitwise complement. -/
def laneOnes : Nat := 2 ^ 64 - 1

/-- Bitwise complement within 64 bits. For `x < 2 ^ 64` this is the usual `~x`. -/
def laneNot (x : Nat) : Nat := laneOnes ^^^ (x % laneMod)

/-- Left rotation by `n < 64` bits. -/
def rotl (x n : Nat) : Nat :=
  ((x <<< (n % laneBits)) ||| (x >>> (laneBits - n % laneBits))) % laneMod

/-! ## Keccak-f[1600] constants

The state is a `List Nat` of 25 lanes indexed `x + 5 * y`. -/

/-- The standard rho rotation offsets, indexed by lane index `x + 5 * y`.
Generated by the usual `(t + 1) * (t + 2) / 2 mod 64` walk and cross-checked
against the published table. -/
def rhoOffsets : List Nat :=
  [ 0,  1, 62, 28, 27,
   36, 44,  6, 55, 20,
    3, 10, 43, 25, 39,
   41, 45, 15, 21,  8,
   18,  2, 61, 56, 14]

theorem rho_offsets_length : rhoOffsets.length = 25 := rfl

/-- Combined rho+pi index table. Entry `d` is `(source lane index, rotation)`:
the pi permutation sends `A[x][y]` to position `[y][2x + 3y]`, so the lane landing
at destination `d = X + 5 * Y` comes from source `(X + 3 * Y) % 5 + 5 * X`, rotated
by that source's rho offset. -/
def rhoPiTable : List (Nat × Nat) :=
  [( 0,  0), ( 6, 44), (12, 43), (18, 21), (24, 14),
   ( 3, 28), ( 9, 20), (10,  3), (16, 45), (22, 61),
   ( 1,  1), ( 7,  6), (13, 25), (19,  8), (20, 18),
   ( 4, 27), ( 5, 36), (11, 10), (17, 15), (23, 56),
   ( 2, 62), ( 8, 55), (14, 39), (15, 41), (21,  2)]

theorem rho_pi_table_length : rhoPiTable.length = 25 := rfl

/-- The rho+pi table is consistent with `rhoOffsets` and with the pi permutation
`dest (X + 5 * Y) <- src ((X + 3 * Y) % 5 + 5 * X)`: a redundant transcription check
so that the literal table above is not trusted on its own. -/
theorem rho_pi_table_matches_permutation :
    rhoPiTable = (List.range 25).map
      (fun d =>
        let X := d % 5
        let Y := d / 5
        let s := (X + 3 * Y) % 5 + 5 * X
        (s, rhoOffsets.getD s 0)) := by
  decide

/-- The 24 Keccak round constants (iota). -/
def roundConstants : List Nat :=
  [0x0000000000000001, 0x0000000000008082, 0x800000000000808a, 0x8000000080008000,
   0x000000000000808b, 0x0000000080000001, 0x8000000080008081, 0x8000000000008009,
   0x000000000000008a, 0x0000000000000088, 0x0000000080008009, 0x000000008000000a,
   0x000000008000808b, 0x800000000000008b, 0x8000000000008089, 0x8000000000008003,
   0x8000000000008002, 0x8000000000000080, 0x000000000000800a, 0x800000008000000a,
   0x8000000080008081, 0x8000000000008080, 0x0000000080000001, 0x8000000080008008]

def numRounds : Nat := 24

theorem round_constants_length : roundConstants.length = numRounds := rfl

theorem round_constants_are_lanes : ∀ c ∈ roundConstants, c < laneMod := by decide

/-! ## The five step mappings -/

/-- theta: `A[x][y] ^= D[x]` where `D[x] = C[x-1] ^ rotl(C[x+1], 1)` and
`C[x]` is the column parity. -/
def theta (a : List Nat) : List Nat :=
  let c : List Nat :=
    (List.range 5).map (fun x =>
      a.getD x 0 ^^^ a.getD (x + 5) 0 ^^^ a.getD (x + 10) 0 ^^^
        a.getD (x + 15) 0 ^^^ a.getD (x + 20) 0)
  let d : List Nat :=
    (List.range 5).map (fun x => c.getD ((x + 4) % 5) 0 ^^^ rotl (c.getD ((x + 1) % 5) 0) 1)
  (List.range 25).map (fun i => a.getD i 0 ^^^ d.getD (i % 5) 0)

/-- rho (lane rotations) and pi (lane permutation), fused via `rhoPiTable`. -/
def rhoPi (a : List Nat) : List Nat :=
  rhoPiTable.map (fun p => rotl (a.getD p.1 0) p.2)

/-- chi: `A[x][y] ^= (~A[x+1][y]) & A[x+2][y]`, rows of five. -/
def chi (a : List Nat) : List Nat :=
  (List.range 25).map (fun i =>
    let x := i % 5
    let y := i / 5
    a.getD i 0 ^^^ (laneNot (a.getD ((x + 1) % 5 + 5 * y) 0) &&& a.getD ((x + 2) % 5 + 5 * y) 0))

/-- iota: XOR the round constant into lane 0. -/
def iota (rc : Nat) (a : List Nat) : List Nat :=
  match a with
  | [] => []
  | l :: rest => (l ^^^ rc) :: rest

/-- One Keccak-f round. -/
def keccakRound (rc : Nat) (a : List Nat) : List Nat :=
  iota rc (chi (rhoPi (theta a)))

/-- The 24 rounds, by structural recursion over the round-constant list. -/
def keccakRounds : List Nat → List Nat → List Nat
  | [], a => a
  | rc :: rcs, a => keccakRounds rcs (keccakRound rc a)

/-- The Keccak-f[1600] permutation. -/
def keccakF (a : List Nat) : List Nat := keccakRounds roundConstants a

/-! ## Sponge -/

/-- Rate in bytes (1088 bits). -/
def rate : Nat := 136

/-- Capacity in bytes (512 bits). -/
def capacity : Nat := 64

/-- Digest length in bytes. -/
def digestBytesLength : Nat := 32

theorem rate_pinned : rate = 136 := rfl

theorem capacity_pinned : capacity = 64 := rfl

theorem rate_plus_capacity_is_state : rate + capacity = 200 := by decide

theorem digest_bytes_length_pinned : digestBytesLength = 32 := rfl

/-- The all-zero 25-lane state. -/
def initialState : List Nat := List.replicate 25 0

theorem initial_state_length : initialState.length = 25 := rfl

/-- Little-endian byte list to lane value; head byte is least significant.
Bytes are reduced `% 256` so the result is a lane for any input list of length
at most 8. -/
def leBytesToLane : List Nat → Nat
  | [] => 0
  | b :: bs => b % 256 + 256 * leBytesToLane bs

/-- Lane to 8 little-endian bytes; the `% 256` extraction is what makes the
output canonical. -/
def laneToLeBytes (n : Nat) : List Nat :=
  (List.range 8).map (fun i => (n >>> (8 * i)) % 256)

theorem lane_to_le_bytes_length (n : Nat) : (laneToLeBytes n).length = 8 := rfl

theorem lane_to_le_bytes_canonical (n : Nat) : ∀ b ∈ laneToLeBytes n, b < 256 := by
  intro b hb
  simp only [laneToLeBytes, List.mem_map] at hb
  obtain ⟨i, _, hi⟩ := hb
  exact hi ▸ Nat.mod_lt _ (by decide)

/-- Split a byte block into `n` little-endian lanes of 8 bytes each. Structural
recursion on the lane count. -/
def bytesToLanes : Nat → List Nat → List Nat
  | 0, _ => []
  | n + 1, bs => leBytesToLane (bs.take 8) :: bytesToLanes n (bs.drop 8)

theorem bytes_to_lanes_length (n : Nat) (bs : List Nat) : (bytesToLanes n bs).length = n := by
  induction n generalizing bs with
  | zero => rfl
  | succ k ih => simp [bytesToLanes, ih]

/-- The 17 rate lanes of one 136-byte block. -/
def blockLanes (bs : List Nat) : List Nat := bytesToLanes 17 bs

theorem block_lanes_length (bs : List Nat) : (blockLanes bs).length = 17 :=
  bytes_to_lanes_length 17 bs

/-- XOR a block's lanes into the state; the state's length is preserved, extra
state lanes (the capacity) pass through unchanged. Structural on the state. -/
def xorLanes : List Nat → List Nat → List Nat
  | [], _ => []
  | s :: ss, [] => s :: xorLanes ss []
  | s :: ss, l :: ls => (s ^^^ l) :: xorLanes ss ls

theorem xor_lanes_length (s l : List Nat) : (xorLanes s l).length = s.length := by
  induction s generalizing l with
  | nil => rfl
  | cons x xs ih =>
    cases l with
    | nil => simp [xorLanes, ih]
    | cons y ys => simp [xorLanes, ih]

/-- Original Keccak padding: append `0x01`, then zeros, then `0x80`, to the next
multiple of the rate; when exactly one byte is missing the two pad bits coincide in
the single byte `0x81`. This is NOT the SHA-3 padding (`0x06 .. 0x80`). -/
def padded (m : List Nat) : List Nat :=
  let k := rate - m.length % rate
  if k = 1 then m ++ [0x81]
  else m ++ (0x01 :: (List.replicate (k - 2) 0 ++ [0x80]))

/-- Absorb phase. `fuel` bounds the number of blocks; `keccak256` passes the padded
length, which is at least the block count, so the recursion always completes. -/
def absorbBlocks : Nat → List Nat → List Nat → List Nat
  | 0, _, s => s
  | _ + 1, [], s => s
  | fuel + 1, b :: bs, s =>
      let block := (b :: bs).take rate
      absorbBlocks fuel ((b :: bs).drop rate) (keccakF (xorLanes s (blockLanes block)))

/-- Squeeze: the 32-byte digest is the first four lanes of the final state,
each written out little-endian. One squeeze pass suffices because
`32 <= rate`. -/
def squeeze (s : List Nat) : List Nat :=
  laneToLeBytes (s.getD 0 0) ++ laneToLeBytes (s.getD 1 0) ++
    laneToLeBytes (s.getD 2 0) ++ laneToLeBytes (s.getD 3 0)

/-- Keccak-256 of a byte string (each element is expected `< 256`; larger entries
are reduced `% 256` when packed into lanes). -/
def keccak256 (m : List Nat) : List Nat :=
  let p := padded m
  squeeze (absorbBlocks p.length p initialState)

/-! ## Structural invariants

The state really is 25 lanes at every point of the sponge, so the four lanes the
squeeze reads are genuine state lanes rather than `getD` defaults. -/

theorem theta_length (a : List Nat) : (theta a).length = 25 := rfl

theorem rho_pi_length (a : List Nat) : (rhoPi a).length = 25 := rfl

theorem chi_length (a : List Nat) : (chi a).length = 25 := rfl

theorem iota_length (rc : Nat) (a : List Nat) : (iota rc a).length = a.length := by
  cases a with
  | nil => rfl
  | cons x xs => simp [iota]

theorem keccak_round_length (rc : Nat) (a : List Nat) : (keccakRound rc a).length = 25 := by
  rw [keccakRound, iota_length, chi_length]

theorem keccak_rounds_length (rcs a : List Nat) (h : a.length = 25) :
    (keccakRounds rcs a).length = 25 := by
  induction rcs generalizing a with
  | nil => exact h
  | cons rc _rcs ih => exact ih _ (keccak_round_length rc a)

theorem keccak_f_length (a : List Nat) (h : a.length = 25) : (keccakF a).length = 25 :=
  keccak_rounds_length roundConstants a h

theorem absorb_blocks_length (fuel : Nat) (m s : List Nat) (h : s.length = 25) :
    (absorbBlocks fuel m s).length = 25 := by
  induction fuel generalizing m s with
  | zero => exact h
  | succ k ih =>
    cases m with
    | nil => exact h
    | cons b bs =>
      exact ih _ _ (keccak_f_length _ (by rw [xor_lanes_length]; exact h))

theorem keccak256_state_has_25_lanes (m : List Nat) :
    (absorbBlocks (padded m).length (padded m) initialState).length = 25 :=
  absorb_blocks_length _ _ _ initial_state_length

/-! ## The two API facts -/

theorem squeeze_length (s : List Nat) : (squeeze s).length = 32 := by
  simp [squeeze, lane_to_le_bytes_length]

theorem keccak256_length (m : List Nat) : (keccak256 m).length = 32 :=
  squeeze_length _

theorem squeeze_canonical (s : List Nat) : ∀ b ∈ squeeze s, b < 256 := by
  intro b hb
  simp only [squeeze, List.mem_append] at hb
  rcases hb with ((h | h) | h) | h
  · exact lane_to_le_bytes_canonical _ b h
  · exact lane_to_le_bytes_canonical _ b h
  · exact lane_to_le_bytes_canonical _ b h
  · exact lane_to_le_bytes_canonical _ b h

theorem keccak256_bytes_canonical (m : List Nat) : ∀ b ∈ keccak256 m, b < 256 :=
  squeeze_canonical _

/-! ## Big-endian byte packing -/

/-- Big-endian: the head byte is the most significant. -/
def bytesToNat : List Nat → Nat
  | [] => 0
  | b :: bs => b * 256 ^ bs.length + bytesToNat bs

theorem bytes_to_nat_nil : bytesToNat [] = 0 := rfl

theorem bytes_to_nat_lt (bs : List Nat) (h : ∀ b ∈ bs, b < 256) :
    bytesToNat bs < 256 ^ bs.length := by
  induction bs with
  | nil => decide
  | cons b rest ih =>
    have hb : b < 256 := h b (by simp)
    have hr : bytesToNat rest < 256 ^ rest.length :=
      ih (fun x hx => h x (by simp [hx]))
    have hstep : b * 256 ^ rest.length + bytesToNat rest
        < 256 * 256 ^ rest.length := by
      have h1 : b + 1 ≤ 256 := hb
      calc b * 256 ^ rest.length + bytesToNat rest
          < b * 256 ^ rest.length + 256 ^ rest.length := by omega
        _ = (b + 1) * 256 ^ rest.length := by rw [Nat.succ_mul]
        _ ≤ 256 * 256 ^ rest.length := Nat.mul_le_mul_right _ h1
    simpa [bytesToNat, List.length_cons, Nat.pow_succ, Nat.mul_comm] using hstep

theorem two_pow_256_eq : (2 : Nat) ^ 256 = 256 ^ 32 := by
  rw [show (256 : Nat) = 2 ^ 8 from rfl, ← Nat.pow_mul]

/-- The digest as an element of `Fin (2 ^ 256)`: the 32 output bytes read
big-endian, exactly as `uint256(keccak256(...))` does on the Solidity side. -/
def digestU256 (m : List Nat) : Fin (2 ^ 256) :=
  ⟨bytesToNat (keccak256 m), by
    have h := bytes_to_nat_lt (keccak256 m) (keccak256_bytes_canonical m)
    rw [keccak256_length] at h
    rw [two_pow_256_eq]
    exact h⟩

theorem digest_u256_val (m : List Nat) : (digestU256 m).val = bytesToNat (keccak256 m) := rfl

/-! ## Test vectors (kernel-proved)

All four are discharged by `decide`, so the kernel itself evaluates Keccak-f[1600]
on these inputs. The first two are the published Keccak-256 vectors; the last two
were produced by an independently written pure-Python Keccak-256 that reproduces
the published pair.

`decide` here evaluates the whole sponge in the kernel; the list literals and the
padded messages also need a raised recursion limit for the elaborator's own
evaluation, so both options are set for the rest of the file. -/

set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

/-- `keccak256 "" = c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470`. -/
theorem keccak256_empty_vector :
    keccak256 [] =
      [197, 210, 70, 1, 134, 247, 35, 60, 146, 126, 125, 178, 220, 199, 3, 192,
       229, 0, 182, 83, 202, 130, 39, 59, 123, 250, 216, 4, 93, 133, 164, 112] := by
  decide

/-- `keccak256 "abc" = 4e03657aea45a94fc7d47ba826c8d667c0d1e6e33a64a036ec44f58fa12d6c45`. -/
theorem keccak256_abc_vector :
    keccak256 [97, 98, 99] =
      [78, 3, 101, 122, 234, 69, 169, 79, 199, 212, 123, 168, 38, 200, 214, 103,
       192, 209, 230, 227, 58, 100, 160, 54, 236, 68, 245, 143, 161, 45, 108, 69] := by
  decide

/-- A 135-byte message: the padding boundary where exactly one byte is left and the
pad collapses to the single byte `0x81`. -/
def padBoundaryMessage : List Nat :=
  [3, 10, 17, 24, 31, 38, 45, 52, 59, 66, 73, 80, 87, 94, 101, 108, 115, 122, 129,
   136, 143, 150, 157, 164, 171, 178, 185, 192, 199, 206, 213, 220, 227, 234, 241,
   248, 255, 6, 13, 20, 27, 34, 41, 48, 55, 62, 69, 76, 83, 90, 97, 104, 111, 118,
   125, 132, 139, 146, 153, 160, 167, 174, 181, 188, 195, 202, 209, 216, 223, 230,
   237, 244, 251, 2, 9, 16, 23, 30, 37, 44, 51, 58, 65, 72, 79, 86, 93, 100, 107,
   114, 121, 128, 135, 142, 149, 156, 163, 170, 177, 184, 191, 198, 205, 212, 219,
   226, 233, 240, 247, 254, 5, 12, 19, 26, 33, 40, 47, 54, 61, 68, 75, 82, 89, 96,
   103, 110, 117, 124, 131, 138, 145, 152, 159, 166, 173]

theorem pad_boundary_message_length : padBoundaryMessage.length = 135 := rfl

theorem pad_boundary_pad_is_single_byte :
    padded padBoundaryMessage = padBoundaryMessage ++ [0x81] := by
  decide

/-- Keccak-256 of the 135-byte padding-boundary message. -/
theorem keccak256_pad_boundary_vector :
    keccak256 padBoundaryMessage =
      [0, 239, 150, 175, 156, 244, 178, 76, 127, 38, 157, 146, 34, 148, 68, 74,
       25, 125, 10, 51, 99, 140, 46, 86, 99, 76, 87, 232, 146, 16, 58, 143] := by
  decide

/-- A 200-byte message: two sponge blocks. -/
def twoBlockMessage : List Nat :=
  [5, 16, 27, 38, 49, 60, 71, 82, 93, 104, 115, 126, 137, 148, 159, 170, 181, 192,
   203, 214, 225, 236, 247, 2, 13, 24, 35, 46, 57, 68, 79, 90, 101, 112, 123, 134,
   145, 156, 167, 178, 189, 200, 211, 222, 233, 244, 255, 10, 21, 32, 43, 54, 65,
   76, 87, 98, 109, 120, 131, 142, 153, 164, 175, 186, 197, 208, 219, 230, 241,
   252, 7, 18, 29, 40, 51, 62, 73, 84, 95, 106, 117, 128, 139, 150, 161, 172, 183,
   194, 205, 216, 227, 238, 249, 4, 15, 26, 37, 48, 59, 70, 81, 92, 103, 114, 125,
   136, 147, 158, 169, 180, 191, 202, 213, 224, 235, 246, 1, 12, 23, 34, 45, 56,
   67, 78, 89, 100, 111, 122, 133, 144, 155, 166, 177, 188, 199, 210, 221, 232,
   243, 254, 9, 20, 31, 42, 53, 64, 75, 86, 97, 108, 119, 130, 141, 152, 163, 174,
   185, 196, 207, 218, 229, 240, 251, 6, 17, 28, 39, 50, 61, 72, 83, 94, 105, 116,
   127, 138, 149, 160, 171, 182, 193, 204, 215, 226, 237, 248, 3, 14, 25, 36, 47,
   58, 69, 80, 91, 102, 113, 124, 135, 146]

theorem two_block_message_length : twoBlockMessage.length = 200 := rfl

theorem two_block_message_padded_length : (padded twoBlockMessage).length = 272 := by
  decide

/-- Keccak-256 of the 200-byte two-block message. -/
theorem keccak256_two_block_vector :
    keccak256 twoBlockMessage =
      [70, 218, 93, 161, 214, 192, 51, 194, 80, 35, 28, 2, 117, 129, 221, 212,
       239, 169, 184, 130, 132, 121, 223, 222, 79, 120, 194, 13, 192, 84, 67, 91] := by
  decide

/-! ## Non-vacuity of the packing layer -/

theorem bytes_to_nat_example : bytesToNat [1, 2, 3] = 66051 := by decide

theorem digest_u256_empty_is_nonzero : 0 < (digestU256 []).val := by
  rw [digest_u256_val, keccak256_empty_vector]
  decide

end Zkp.Implementation.Keccak256
